### ISSUE TITLE
Allow rearranging of fields within a record

### ISSUE THREAD

**Issue by dotdrew** [padloc/padloc#171]
It would be very helpful if it was possible to rearrange the order of fields within a record

e.g. if I update my password for gmail but want to keep my previous password in Padlock, rather than having "Gmail: Username, 2017 Password, 2018 Password" or having to manually retitle each record, I could just add it to the gmail record and move it up the list of fields so it shows at the top of the fields preview.

**Comment by MaKleSoft** [comment]
We're currently working on revamping the UI of the record view and rearranging fields is part of the roadmap. I'll leave this open so you can track the progress.

**Comment by MaKleSoft** [comment]
This is now possible in v3 😎
