### ISSUE TITLE
Escape doesn't dismiss popup

### ISSUE THREAD

**Issue by pwasiewicz** [padloc/padloc#182]
While editing single field
![popup](https://user-images.githubusercontent.com/8725777/39857377-6f342f48-5433-11e8-8e31-87f2ca4411bd.jpg)
I hit the Escape button. I'd expected editing popup dismiss, but underlying record details is dismissed instead:
![popup_after_esc](https://user-images.githubusercontent.com/8725777/39857418-91507d3e-5433-11e8-8dd2-5a7e596cc157.jpg)

**Comment by MaKleSoft** [comment]
Good catch!
