### ISSUE TITLE
Password generator popup does not disappear on auto-lock.

### ISSUE THREAD

**Issue by brightsquare** [padloc/padloc#194]
Steps to reproduce:
1. Setup auto lock (I use 1 min)
2. Open an entry and open the password generator
3. Wait for auto lock

Expected result: Padlock is locked with password generator disappeared
**Actual result**: Padlock is locked with password generator **still active**. Hitting apply does not however save the password.

Padlock v2.7.2 (latest)
macOS 10.13.4

![Actual result](https://user-images.githubusercontent.com/11938094/42448780-b5da7df4-83c1-11e8-9951-fe19e876b692.png)

**Comment by MaKleSoft** [comment]
Good catch. Thanks!
