### ISSUE TITLE
Password generation fails in certain conditions

### ISSUE THREAD

**Issue by dphiffer** [padloc/padloc#200]
To replicate:

1. create new entry
2. generate password (save)
3. add field
4. generate password (fails)

Password generation works again if you save an empty field and then edit it.

![padlock-bug](https://user-images.githubusercontent.com/38114/44855515-3b220a00-ac39-11e8-9fd7-a08934d36936.gif)

**Comment by MaKleSoft** [comment]
@dphiffer Interesting... thanks for the detailed report! I'll look into it

**Comment by dphiffer** [comment]
It's kind of an edge case, but I have a habit of generating strong passwords for security questions, which is hard to do currently.

**Comment by alxmiron** [comment]
Have some similar issue too. v2.7.2 macOS
![dec-21-2018 17-54-17](https://user-images.githubusercontent.com/10484318/50351098-cbb68a00-0549-11e9-8671-80ef24e8f5ad.gif)

**Comment by MaKleSoft** [comment]
Thanks again for all the detailed feedback! The gifs are really quite helpful. This particular bug has already been fixed in the v3 branch (the whole edit experience has been revamped). I'll keep the issue open until v3 is merged though.
