### ISSUE TITLE
Support of flatpaks (or/and snap)

### ISSUE THREAD

**Issue by antonincms** [padloc/padloc#201]
Hello,

Even if appimage is a nice format, It isn't natively integrated in any major gnu/linux distributions, as Fedora and Ubuntu, using respectively Flatpaks and Snap. Beyond that, you could ship your app on a repo, as flathub. 

I was initially going to give a shot to your app, and this package is very efficient for that, as it don't need installation, not any package manager, but the fact that it would be upgradable only manually, alone in a folder, and not integrated at all in my system isn't really enjoying me to keep it long term.

So the Is there any reason not to try to package it with other universal packages ?

Doc : 
- Flatpak : 
  Packaging : http://docs.flatpak.org/en/latest/first-build.html
  Flathub submission : https://github.com/flathub/flathub/wiki/App-Submission
- Snap : 
  Packaging : https://docs.snapcraft.io/build-snaps/languages
  Snapcraft submission : https://docs.snapcraft.io/build-snaps/publish

**Comment by MaKleSoft** [comment]
> but the fact that it would be upgradable only manually

Padlock does support auto updates, but distribution via package managers may have some other advantages. We'll be reevaluating distribution formats for v3. I'll keep this issue open for now.

**Comment by AntoninCamus** [comment]
Flatpak for example (the one I know the most, and that I find the most promising) need learning (you can't call gettext as you did before, and you need to call libs from shared runtimes as freedesktop to avoid duplicating libs), but it appears to me as a better universal packaging system.

**Comment by rugk** [comment]
Yes, would also like a flatpak version. Snap is way too Ubuntu-specific (no sandboxing in other distros e.g.).
