### ISSUE TITLE
Using lockbox/ Firefox accounts as sync storage

### ISSUE THREAD

**Issue by mangas** [padloc/padloc#204]
I was wondering if this is something that could actually be done, the clients for lockbox are open source and currently being developed. It also looks like padlock-cloud is in the works, this could be an interesting option. Building on top of an already existing backend. 

What do you think? I'm not familiar with the padlock codebase but if this is something you'd be interested in having I'd be happy to help.

**Comment by mangas** [comment]
I assume you mean OAuth? 

https://lockbox.firefox.com/architecture/fxa.html
https://lockbox.firefox.com/architecture/sync.html

**Comment by MaKleSoft** [comment]
Closing this since Lockbox/Lockwise won't be supported anymore.
