### ISSUE TITLE
Iphone app add new field with long content fails

### ISSUE THREAD

**Issue by pkilpo** [padloc/padloc#206]
How to reproduce: Create new field, paste a long content eg. email which may contain links etc. Keyboard stays on, nothing shown of data, cursor is mislocated, cannot find "save" button to save new field. Newest version on AppStore 2.Jan.2018.
Tried the same with windows version it worked there no problems.

**Comment by MaKleSoft** [comment]
Thanks for reporting this! Should be fixed in v3.
