### ISSUE TITLE
Checked for pwned passwords

### ISSUE THREAD

**Issue by ghost** [padloc/padloc#208]
Hi,
maybe you can create a option to check if a password is listed here:

https://haveibeenpwned.com

I know that lot of password managers already use it.
Thanks.

**Comment by beli3ver** [comment]
Are they any updates on this?

**Comment by MaKleSoft** [comment]
Not yet, sorry. This is on our long list of advanced features we're planning to implement once v3 is released. Can't really give an eta yet though.

**Comment by MaKleSoft** [comment]
Finally! https://github.com/padloc/padloc/pull/414
Sorry for the long wait 😅
