### ISSUE TITLE
Backup Question to Padlock cloud keeps appearing

### ISSUE THREAD

**Issue by DavidS3141** [padloc/padloc#209]
Simple question:

Is it supposed to be like this, that every time I use Padlock, the question of signing in to Padlock cloud for backup reasons keeps appearing, or should this be a one-time thing and is just a bug on my end? I am asking because this gets really annoying. Because every time I hit "Do nothing", I am getting surer of my answer, so I am probably at around 125% confidence already ;)

**Comment by MaKleSoft** [comment]
@DavidS3141 You're right, that reminder should only be shown once, or at least offer the user to turn it off. This probably won't be fixed before the release of v3 though, so I hope you can put up with those popups for a while longer ;)
