### ISSUE TITLE
Biometric Authentication (Fingerprint, FaceID etc.)

### ISSUE THREAD

**Issue by dploeger** [padloc/padloc#21]
Common password managers support the unlocking of the vault using the iOS TouchID fingerprint identification framework.

I will post more information to this issue about the implementation and possible ways in Polymer or cordova.

**Comment by dploeger** [comment]
This would be a cordova integration using i.e. the [cordova-touch id plugin](https://github.com/EddyVerbruggen/cordova-plugin-touch-id). Integration notes are available in the plugin's Readme.

However, it seems that (at least in form of that plugin) can only lock or unlock the app, it cannot securely save the vault's password. Thus I'm not sure, wether it could be made to work with padlock...

**Comment by MaKleSoft** [comment]
This is a tricky one. While I can see this as being very useful, it has a couple of strong implications on security. Padlocks data integrity and security is based on the secrecy of the master password. Using touch id would require relying on the iOS keychain to hold the master password. Relying on OS 'secure' storage mechanisms is dangerous, as was demonstrated by [recent discoveries of severe vulnerabilities](http://arstechnica.com/security/2015/06/serious-os-x-and-ios-flaws-let-hackers-steal-keychain-1password-contents/) in iOS Keychain. So right now I am very hesitant to consider this.

**Comment by cclafferty** [comment]
Dashlane's iOS app will allow you to enable TouchID to unlock the app but only if it's been unlocked already and the app has been restored from running in the background. I feel that this gives the best of both worlds. You still need the master password to unlock the app to begin with, then any subsequent unlocks can happen with TouchID on it's own. I believe they also employ a timeout so that if the app has been in the background for a while then you'll need to enter the master password again.

**Comment by MaKleSoft** [comment]
@cclafferty Yes, this was something I was considering as well, but since this obviously adds less to the user experience than what @dploeger suggested I'm not sure if its worth implementing.

**Comment by cclafferty** [comment]
I see what you're saying but would only add this: I use very long passwords
for my password managers. They are what you'd consider 'strong'. The
problem with that however is that every time I switch apps I have to
re-enter what is already a very difficult password to type out on a phone
over again.

From this perspective TouchID is not something I'd trust indefinitely with
my passwords BUT I do appreciate that its security is temporary when I need
the app to be more convenient. Of course for those who value security above
everything else you could have an option to not use TouchID at all (I know
some people don't like it).

Anyway this is a great app and an exciting project. Looking forward to
contributing more.

**Comment by dploeger** [comment]
I think, that would also be my suggestion: completely support it (for permanent unlock), disable it as default and show a warning when enabling it.

**Comment by MaKleSoft** [comment]
Ok guys, thanks for all your input! I'll consider all your feedback when I create a roadmap for the next releases.

**Comment by TheLastDestroyer** [comment]
Just looking to see if there has been any progress on this. I have just started using padlock and am loving it so far, but being able t po use my fingerprint, on android though, to reunlock the app from background would greatly add to my experience. I too use a very long master password and it's a pain having to re enter it between copying username and passwords. Some sort of time out might also help with this and be just as effective and probably easier.

**Comment by MaKleSoft** [comment]
@TheLastDestroyer There are still no concrete plans to implement this feature. However, you'll be happy to hear that we've overhauled the auto-locking behaviour for the next release. Padlock will now only lock after a certain period of time after you leave the app so you won't have to enter your password every time you switch apps.

**Comment by peterloron** [comment]
I would really like to see this implemented as an option. Thanks.

**Comment by MaKleSoft** [comment]
Still on the fence about this and definitely not high-priority but we'll probably revisit this at some point. Closing this for now.

**Comment by MaKleSoft** [comment]
Biometric unlock is now available in the Padloc 3 Beta on Android and iOS. So we can finally close this. 🎉

**Comment by inikolic** [comment]
YAHAAAAY!!!!

 

THANK YOU!  THANK YOU!  THANK YOU!

 

Best regards,

Ivan

**Comment by cclafferty** [comment]
Excellent work. Glad to hear this feature has made its way into a great piece of software. Thank you!
