### ISSUE TITLE
Countdown timer covers quick copies of the bottom entry

### ISSUE THREAD

**Issue by smithpsean** [padloc/padloc#214]
After copying a field the countdown timer covers the bottom entry in the selection list.  This makes it so that If I copied the username, I cant just then copy the password because its covered.  The entire right screen is empty during this time.  It could be used for the timer.

**Comment by MaKleSoft** [comment]
Thanks for the feedback! We'll fix this as part of the v3 release. In the meantime, you can make the clipboard notification go away by clicking the "clear" button which should then allow you to copy the next field.
