### ISSUE TITLE
Looking For Beta Testers!

### ISSUE THREAD

**Issue by MaKleSoft** [padloc/padloc#221]
As some of you may now, we just [announced the upcoming release of Padloc 3](https://padloc.app/news/announcing-v3/)! 🕺

Before going live, we'd like to spend a couple of weeks gathering feedback, adding polish and of course fixing any bugs that we've missed so far. Specifically, we're looking to test the new [organizations / shared vaults feature](https://padloc.app/news/announcing-v3/#introducing-organizations-and-shared-vaults), so if you'd be willing to test Padloc in your team, company or family, that would be incredibly valuable to us! 

So if you're interested in becoming a beta tester, please shoot me an email at martin@padloc.app!

**Comment by rawtaz** [comment]
This can perhaps be closed now? :)

**Comment by MaKleSoft** [comment]
@rawtaz Yeah perhaps you're right 😉
