### ISSUE TITLE
Make a better effort at guessing field types when importing

### ISSUE THREAD

**Issue by MaKleSoft** [padloc/padloc#223]
Any data not exported from Padloc 3 directly will probably not have any field metadata associated with it. We can make an educated guess based on field name and value though, and a sporadic version of that is implemented here: https://github.com/padloc/padloc/blob/master/packages/core/src/item.ts#L221-L237

Correctly guessing field types like phone numbers, email addresses and urls during import would greatly improve use experience so we should probably put a little more effort into these heuristics.  These are the basic strategies I can think of.

- Match against common field names like ("username", "password", "url", etc.)
- Match against common field names in other languages
- Pattern match things that have a clear structure, like emails, urls, phone numbers, credit cards etc.

**Comment by BrunoBernardino** [comment]
Fixed by #411
