### ISSUE TITLE
iOS 3.0.4 field validation popup out of focus

### ISSUE THREAD

**Issue by moritzheiber** [padloc/padloc#227]
When I don’t fill a required field for sign-up on the latest iOS version (3.0.4) the popup suggesting for me to enter the data is a little out of whack:

![Image](https://i.imgur.com/5ffUWhO.jpg)

This is on iOS 13.1 on an iPhone 8 Plus.

**Comment by MaKleSoft** [comment]
Hi Moritz,

hm, this is a native iOS UI element so I don't think we can do much about
that. Hopefully this is just a bug in iOS 13 and will go away soon. Thanks
for reporting it though!

Thanks,
Martin
