### ISSUE TITLE
Key Encryption fails in Chrome 78

### ISSUE THREAD

**Issue by mandusm** [padloc/padloc#229]
When accessing the Padlock PWA application using Chrome Browser (see version info below), when trying to register or log in, the verification fails because of key encryption errors. 

This process seems to work just fine when accessing the PWA through Safari on OSX Catalina.

<img width="571" alt="Screen Shot 2019-11-01 at 4 13 04 PM" src="https://user-images.githubusercontent.com/4682490/68061556-b4e0d800-fcc2-11e9-99d7-1da294d8e9ed.png">
<img width="681" alt="Screen Shot 2019-11-01 at 4 12 23 PM" src="https://user-images.githubusercontent.com/4682490/68061559-b7433200-fcc2-11e9-9f46-913fd5fe333a.png">
<img width="404" alt="Screen Shot 2019-11-01 at 4 10 37 PM" src="https://user-images.githubusercontent.com/4682490/68061561-ba3e2280-fcc2-11e9-8bb8-73a08a26ec45.png">

Other Information Worth considering: 
Works on Safari: 
<img width="276" alt="Screen Shot 2019-11-01 at 4 15 33 PM" src="https://user-images.githubusercontent.com/4682490/68061581-e063c280-fcc2-11e9-97fb-851851ffeb5e.png">
<img width="200" alt="Screen Shot 2019-11-01 at 4 15 43 PM" src="https://user-images.githubusercontent.com/4682490/68061584-e35eb300-fcc2-11e9-8009-673cd6ad6805.png">

**Comment by MaKleSoft** [comment]
Hm, interesting. Can't reproduce this on either Chrome 78 nor Chrome 79 on MacOS Mojave.  The error message suggests that the `window.subtleCrypto` object isn't available. The only reason I can think of why this may be the case is if the web client was accessed via http instead of https but that wouldn't be possible with the official web client. Are you hosting your own version perhaps?

**Comment by mandusm** [comment]
Yip. Closing this issue. 
I was doing some dev/test on my local machine to add support for DynamoDB storage and Email via SES. 

Running straight over docker using http.
My bad.

**Comment by MaKleSoft** [comment]
@mandusm You should still be able to test over localhost: https://www.chromestatus.com/feature/6269417340010496

> add support for DynamoDB storage and Email via SES

Looking forward to the PR :)
