### ISSUE TITLE
Sort items by "Recently Used"

### ISSUE THREAD

**Issue by mandusm** [padloc/padloc#231]
It would be great if we could have the sorting functionality from `v2` back in `v3`.
Recently used items were stacked at the top of the list when opening the app, making for ease of access of items.

**Comment by MaKleSoft** [comment]
I think a good variation of the feature that is more consistent with the new UX would be a new "filter" in the main menu, alongside favorites:

![image](https://user-images.githubusercontent.com/1270940/68461356-58257600-020a-11ea-83fa-9dac13818040.png)

@mandusm what do you think?

**Comment by mandusm** [comment]
Yeah. I like it. That feels consistent with the new UI design and solves the problem. 
Maybe giving the user the ability to set the "default filter" to show at login? 

Like. I like to see recently used, or someone else would like to see favorites as their "landing" page after login.
