### ISSUE TITLE
Moving to different vault actually copies items

### ISSUE THREAD

**Issue by raphmim** [padloc/padloc#233]
After trying to move all my items from my Personal Vault to my Organization's vault, all items remained in the Personal Vault. I had to delete them all.

This is on Mac OS, PadLoc v3.0.8, with over 400 items that were just imported from a CSV file, and running over the 50 item limit. Note that I tried with just one item, and it worked properly (moving it instead of copying it)

**Comment by MaKleSoft** [comment]
Hm, that's interesting. Managed to reproduce it once, but then it worked properly all subsequent times. Maybe is has something to do with the large number of items you were moving. I'll keep an eye on it.

**Comment by MaKleSoft** [comment]
I believe this should be fixed now. Let me know if it still happens.
