### ISSUE TITLE
Multi-select: Initial selection should be empty

### ISSUE THREAD

**Issue by Raph33** [padloc/padloc#235]
Not sure if it's a bug or a feature, but on Mac clicking the Select button selects all items in the current view. This seems risky and it may be preferable that no item would be selected by default, with the option to select all.

**Comment by MaKleSoft** [comment]
Actually, that's the intended behavior, but I understand your concern. I think you're right that selecting none by default is the safer choice, so I guess we'll change it.

**Comment by Raph33** [comment]
Great, thank you!
