### ISSUE TITLE
Problems with signup flow in Firefox

### ISSUE THREAD

**Issue by Raph33** [padloc/padloc#236]
For one user, hovering over the password showed an empty field (see attached).
For another user, clicking the "continue" button after repeating the master password didn't do anything. 
 
<img width="511" alt="Screen Shot 2019-11-07 at 3 32 15 PM" src="https://user-images.githubusercontent.com/27868414/68425304-d5ea7280-0173-11ea-9b96-a52836b0b3d2.png">

**Comment by MaKleSoft** [comment]
The issue title mentions invites, so I'm assuming this happened after following the invite link? Does the same problem occur if the "start fresh", i.e. by going to "https://web.padloc.app/signup"?

**Comment by Raph33** [comment]
That's correct, this happened after following the invite link. 
I just checked and the same thing occurs when going to https://web.padloc.app/signup

**Comment by MaKleSoft** [comment]
Got it. I'll look into it!

**Comment by MaKleSoft** [comment]
@Raph33 Can't reproduce this on latest Firefox (70.0.1). Which version did you try this on? On which OS? Also, could you please open dev tools and post any errors here?

**Comment by MaKleSoft** [comment]
Nevermind, found the problem. It's related to https://github.com/padloc/padloc/issues/230. Fixing it now.

**Comment by MaKleSoft** [comment]
> For one user, hovering over the password showed an empty field (see attached).

This should be fixed now.

> For another user, clicking the "continue" button after repeating the master password didn't do anything.

Not sure if that's related. @Raph33 Can you check if this is still a problem?

**Comment by Raph33** [comment]
Both issues seem to be fixed!
