### ISSUE TITLE
Backarrow confusing when navigating items

### ISSUE THREAD

**Issue by raphmim** [padloc/padloc#240]
See attached: I suggest replacing the backarrow with an exit cross; this would clarify that we are exiting/closing the item rather than returning to a previous dialog.

In some cases, there is no previous dialog--we just opened an item and want to close it--and the exit cross would make that clearer.

In other cases, like when creating or editing an item, it gives the impression that we would return to the previous dialog while it actually closes the item.

<img width="563" alt="Screen Shot 2019-11-08 at 9 31 46 AM" src="https://user-images.githubusercontent.com/27868414/68484479-51e3c980-020b-11ea-8478-3c2e7f1771c4.png">

**Comment by MaKleSoft** [comment]
No longer relevant for v4 due to UI changes.
