### ISSUE TITLE
Editing item fails

### ISSUE THREAD

**Issue by Raph33** [padloc/padloc#244]
On desktop (for Mac OS, Padloc v3.0.8), editing an item (changing item name, removing fields, etc) doesn't work the first time:
1. Open item
2. Edit
3. Save
4. Exit
=> The changes are not saved. 

Editing a second time works, with the changes saved.

**Comment by MaKleSoft** [comment]
Pretty sure this is fixed in v2.0.10. Can you install the latest (Settings > Updates > Check For Updates) and try again please?

**Comment by Raph33** [comment]
Yes, it looks like it's been fixed. Thank you!
