### ISSUE TITLE
Padloc Emergency Access

### ISSUE THREAD

**Issue by mandusm** [padloc/padloc#245]
Now that we have Vault sharing capability, it would be great to provide "Emergency Access" capabilities to the system. 

Emergency Access offers an easy way to give others the passwords and logins they’d need to manage accounts on your behalf after an unexpected emergency or death. With Emergency Access, you can prepare for the unexpected and ensure your loved ones don’t get locked out of important accounts. In the event of an emergency or crisis, your designated Emergency Access contact(s) can request access to your account and securely receive the passwords and notes stored in your vault.

**Comment by MaKleSoft** [comment]
Yep, that's definitely something we're planning to add at some point! I can't give an exact eta yet but you can probably expect an announcement sometime early next year :)

**Comment by Raph33** [comment]
@mandusm interesting idea. Could you describe in more details how that would work? Who would have the power to decide that there is indeed an "emergency", and how would they verify it? 

Wouldn't it be better for a user to simply create a Vault specifically for that purpose and share it with their most trusted contacts. Those contacts would be trusted to not use the items in the Vault until needed.

**Comment by MaKleSoft** [comment]
> Wouldn't it be better for a user to simply create a Vault specifically for that purpose and share it with their most trusted contacts. Those contacts would be trusted to not use the items in the Vault until needed.

That is one way to do it, yes. But there are plenty of things you wouldn't want other people to have access to while you are still alive, like social media accounts, certain financial assets etc.

> Who would have the power to decide that there is indeed an "emergency", and how would they verify it?

That is a good question. We are envisioning some sort of "dead man's switch". For example, the user could specify a certain time frame of inactivity after which emergency protocols would be triggered. This could be anything from a week to a couple of months, depending on the nature of the data and the preferences of the user.

**Comment by Raph33** [comment]
I like the idea of a "dead person's switch".

Another potential way of doing it would be to have users select several trusted contacts, and only these trusted contacts could only access the Vault together. Something along the lines of https://darkcrystal.pw/

**Comment by MaKleSoft** [comment]
That's definitely an intriguing idea, but probably a bit excessive for most use cases. We'll keep it in mind though, as it would be great as an *advanced* security measure for the paranoid, especially in combination with a dead man's switch.

**Comment by combinatorist** [comment]
If you want to give emergency access to someone you live with, you can:
1. seal your master password in a privacy envelope
1. sign and date your name over the seal
1. take a photo
1. hide it somewhere only the two of you know or have access

This still requires trust of the other person, but it also indicates tampering (i.e. whether that trust has been violated). One great weakness with this system, though, is it may take a very long time before you realize the information has been accessed.

---

I've thought some about it and I don't see how Padloc could implement this digitally without violating its [No Trust Required](https://github.com/padloc/padloc/blob/master/security.md#no-trust-required) principle. If you build a deadman's switch, then you're trusting Padloc to hold a secret it can reveal later. But, if you don't build the switch, then, you're trusting the other person with credentials now.

My preference is to trust the person, but require reporting when they access the data (like in the analog algorithm above). Is there a trustless way to do this in padloc? Actually, this raises the question whether shared vaults show the last time another user accessed them (I haven't got padloc 3 to work yet on linux). And if so, is that reporting trustless? I suppose you could make it trustless, by re-encrypting the cloud data every time it is accessed.

**Comment by MaKleSoft** [comment]
> If you build a deadman's switch, then you're trusting Padloc to hold a secret it can reveal later.

Not quite. The idea is to give the encryption key to the trustee but withhold the (encrypted) data itself until certain requirements are met. That way we can manage access to the data (to a certain degree) without ever having access to it ourselves, thus not violating the No Trust Required principle.

> Actually, this raises the question whether shared vaults show the last time another user accessed them (I haven't got padloc 3 to work yet on linux). And if so, is that reporting trustless?

Note that the No Trust Required principle only applies to data that is considered secret (i.e. anything encrypted inside vaults). Any metadata including vault names, organization members etc. are by necessity visible to the server and cannot be end-to-end encrypted.

**Comment by combinatorist** [comment]
Ok, thanks for quick responses, @MaKleSoft!

**Comment by MaKleSoft** [comment]
Closing this is favour of https://github.com/padloc/padloc/issues/435 and https://github.com/padloc/padloc/issues/436. @mandusm @raphmim @combinatorist thanks for all your input thus far!
