### ISSUE TITLE
Can't compile on arch

### ISSUE THREAD

**Issue by BooneyNoobington** [padloc/padloc#249]
Following the rather simplie instructions gives the following result:

```
[padloc@d4 ~]$ git clone https://github.com/padloc/padloc
Klone nach 'padloc' ...
remote: Enumerating objects: 977, done.
remote: Counting objects: 100% (977/977), done.
remote: Compressing objects: 100% (484/484), done.
remote: Total 21848 (delta 694), reused 722 (delta 483), pack-reused 20871
Empfange Objekte: 100% (21848/21848), 23.46 MiB | 2.11 MiB/s, Fertig.
Löse Unterschiede auf: 100% (15278/15278), Fertig.
[padloc@d4 ~]$ cd padloc/
[padloc@d4 padloc]$ npm install

> padloc@3.0.10 postinstall /srv/padloc/padloc
> npm run bootstrap


> padloc@3.0.10 bootstrap /srv/padloc/padloc
> lerna bootstrap

lerna notice cli v3.16.4
lerna info Bootstrapping 8 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in '@padloc/pwa'
lerna ERR! npm install stdout:

> sharp@0.22.1 install /srv/padloc/padloc/packages/pwa/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

make: Verzeichnis „/srv/padloc/padloc/packages/pwa/node_modules/sharp/build“ wird betreten
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
make: Verzeichnis „/srv/padloc/padloc/packages/pwa/node_modules/sharp/build“ wird verlassen

lerna ERR! npm install stderr:
info sharp Using cached /srv/padloc/.npm/_libvips/libvips-8.7.4-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=13.3.0 runtime=node arch=x64 libc= platform=linux)
../src/stats.cc: In Elementfunktion »virtual void StatsWorker::HandleOKCallback()«:
../src/stats.cc:130:37: Fehler: keine passende Funktion für Aufruf von »v8::Array::Set(int&, v8::Local<v8::Object>&)«
  130 |         channels->Set(i, channelStat);
      |                                     ^
In Datei, eingebunden von /srv/padloc/.cache/node-gyp/13.3.0/include/node/node.h:63,
                 von ../src/stats.cc:19:
/srv/padloc/.cache/node-gyp/13.3.0/include/node/v8.h:3547:37: Anmerkung: candidate: »v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)«
 3547 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/srv/padloc/.cache/node-gyp/13.3.0/include/node/v8.h:3547:37: Anmerkung:   Kandidat erwartet 3 Argumente, 2 angegeben
/srv/padloc/.cache/node-gyp/13.3.0/include/node/v8.h:3550:37: Anmerkung: candidate: »v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)«
 3550 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/srv/padloc/.cache/node-gyp/13.3.0/include/node/v8.h:3550:37: Anmerkung:   Kandidat erwartet 3 Argumente, 2 angegeben
make: *** [sharp.target.mk:132: Release/obj.target/sharp/src/stats.o] Fehler 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:219:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! System Linux 5.4.2-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/padloc/padloc/packages/pwa/node_modules/sharp
gyp ERR! node -v v13.3.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /srv/padloc/.npm/_logs/2019-12-07T15_02_46_692Z-debug.log

lerna ERR! npm install exited 1 in '@padloc/pwa'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! padloc@3.0.10 bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the padloc@3.0.10 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /srv/padloc/.npm/_logs/2019-12-07T15_02_47_118Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! padloc@3.0.10 postinstall: `npm run bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the padloc@3.0.10 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /srv/padloc/.npm/_logs/2019-12-07T15_02_47_347Z-debug.log
```

I googled the problem but don't really understand whats going wrong here.

What am I doing wrong?

Thanks in advance
Markus

**Comment by MaKleSoft** [comment]
Looks like it's trying and failing to build libvips from source. Googling the error probably doesn't yield any results because the output is partially in German. Perhaps you could change the language of your dev invironment to English so you'll get more googleable error messages?

**Comment by BooneyNoobington** [comment]
[padloc@d4 padloc]$ npm install

> padloc@3.0.10 postinstall /srv/padloc/padloc
> npm run bootstrap


> padloc@3.0.10 bootstrap /srv/padloc/padloc
> lerna bootstrap

lerna notice cli v3.16.4
lerna info Bootstrapping 8 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in '@padloc/pwa'
lerna ERR! npm install stdout:

> sharp@0.22.1 install /srv/padloc/padloc/packages/pwa/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

make: Entering directory '/srv/padloc/padloc/packages/pwa/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
make: Leaving directory '/srv/padloc/padloc/packages/pwa/node_modules/sharp/build'

lerna ERR! npm install stderr:
info sharp Using cached /srv/padloc/.npm/_libvips/libvips-8.7.4-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=13.3.0 runtime=node arch=x64 libc= platform=linux)
../src/stats.cc: In member function 'virtual void StatsWorker::HandleOKCallback()':
../src/stats.cc:130:37: error: no matching function for call to 'v8::Array::Set(int&, v8::Local<v8::Object>&)'
  130 |         channels->Set(i, channelStat);
      |                                     ^
In file included from /srv/padloc/.cache/node-gyp/13.3.0/include/node/node.h:63,
                 from ../src/stats.cc:19:
/srv/padloc/.cache/node-gyp/13.3.0/include/node/v8.h:3547:37: note: candidate: 'v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)'
 3547 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/srv/padloc/.cache/node-gyp/13.3.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/srv/padloc/.cache/node-gyp/13.3.0/include/node/v8.h:3550:37: note: candidate: 'v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)'
 3550 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/srv/padloc/.cache/node-gyp/13.3.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
make: *** [sharp.target.mk:132: Release/obj.target/sharp/src/stats.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:219:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! System Linux 5.4.2-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/padloc/padloc/packages/pwa/node_modules/sharp
gyp ERR! node -v v13.3.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by MaKleSoft** [comment]
This seems to be a know issue with sharp v0.22 and nodejs v13: https://github.com/lovell/sharp/issues/1909

Upgrading to sharp v0.23 would solve the issue but unfortunately it is a transitive dependency of favicons-webpack-plugin so upgrading is not straighforward. See also https://github.com/jantimon/favicons-webpack-plugin/issues/179 and https://github.com/itgalaxy/favicons/issues/292.

I haven't been too happy with that plugin for a while since its a pretty big resource hog and significantly increases build time so we'll probably remove it at some point, anyway. In the meantime, temporarily downgrading to node 12 (e.g. using [nvm](https://github.com/nvm-sh/nvm/blob/master/README.md)) should fix the problem as well.
