### ISSUE TITLE
Support hosting PWA on a subpath

### ISSUE THREAD

**Issue by MaKleSoft** [padloc/padloc#252]
Currently the app expects various scripts and assets to be located under the root path within the pwa host url. This leads to problem is the app ist hosted on a subpath (e.g. `https://myserver.com/padloc/`. We'll probably need another environment variable to allow customizing this. Relevant lines:

https://github.com/padloc/padloc/blob/master/packages/app/src/mixins/service-worker.ts#L44
https://github.com/padloc/padloc/blob/master/packages/pwa/webpack.config.js#L18

**Comment by mpfaff** [comment]
Any update on this?

**Comment by MaKleSoft** [comment]
@mpfaff not yet, sorry!

**Comment by mpfaff** [comment]
No problem! I managed to get it working on a subdomain instead.

**Comment by mdowais** [comment]
Why not use Proxy Paths? @mpfaff

**Comment by mpfaff** [comment]
> Why not use Proxy Paths? @mpfaff

I posted that more than 2 years ago. I no longer use padloc. The frontend uses paths relative to the host root (so something like `/foo`) rather than a configurable root url (which could include a subpath). Proxy path is completely unrelated.

**Comment by BrunoBernardino** [comment]
I'm closing this since there isn't many requests, and it's feasible with an nginx `proxy_pass`, like mentioned in https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass
