### ISSUE TITLE
Won't start on Debian

### ISSUE THREAD

**Issue by lewebster** [padloc/padloc#257]
I tried running the new Version on Debian Stretch and Buster but won't get it to start.
Tried fresh Buster install with only node.js 12 an git installation as mentioned in the README.md

```
root@myserver:~/padloc# PL_DATA_DIR=~/padloc-data PL_SERVER_PORT=3000 PL_PWA_PORT=8080 npm run start

> padloc@3.0.10 start /root/padloc
> npm run pwa:build && lerna run --scope '@padloc/{server,pwa}' --parallel start


> padloc@3.0.10 pwa:build /root/padloc
> lerna run build --scope @padloc/pwa

lerna notice cli v3.16.4
lerna info filter [ '@padloc/pwa' ]
lerna info Executing command in 1 package: "npm run build"
lerna ERR! npm run build exited 1 in '@padloc/pwa'
lerna ERR! npm run build stdout:

> @padloc/pwa@3.0.13 build /root/padloc/packages/pwa
> webpack


lerna ERR! npm run build stderr:
sh: 1: webpack: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @padloc/pwa@3.0.13 build: `webpack`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @padloc/pwa@3.0.13 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-30T14_56_38_858Z-debug.log

lerna ERR! npm run build exited 1 in '@padloc/pwa'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! padloc@3.0.10 pwa:build: `lerna run build --scope @padloc/pwa`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the padloc@3.0.10 pwa:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-30T14_56_38_893Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! padloc@3.0.10 start: `npm run pwa:build && lerna run --scope '@padloc/{server,pwa}' --parallel start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the padloc@3.0.10 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-30T14_56_38_913Z-debug.log
```

[2019-12-30T14_56_38_858Z-debug.log](https://github.com/padloc/padloc/files/4010126/2019-12-30T14_56_38_858Z-debug.log)
[2019-12-30T14_56_38_893Z-debug.log](https://github.com/padloc/padloc/files/4010127/2019-12-30T14_56_38_893Z-debug.log)
[2019-12-30T14_56_38_913Z-debug.log](https://github.com/padloc/padloc/files/4010128/2019-12-30T14_56_38_913Z-debug.log)

**Comment by MaKleSoft** [comment]
Hm, not getting much useful information from those logs, unfortunately. Can you please try the following (from the project root):

```sh
cd packages/pwa
npx webpack
```

**Comment by lewebster** [comment]
Ok, that showed me the Problem.
While executing "npx webpack" i got an error message that said, that the current user "MyUserName" can't access the dev dir "/root/.cache/node-gyp/12.14.0".
I was confused, because i was running the command as root.
The Problem seems to be, that i wasn't running the command while being logged in as root but in a sudoed bash session that was started from logging in with my "normal" useraccount and running "sudo bash".
Still don't know what the exact access problem is but running all the npm install and start commands as normal user or by being logged in directly as root works fine.
Thank you for the quick response.
