### ISSUE TITLE
When creating an item while in a vault, the item should be placed in that vault by default

### ISSUE THREAD

**Issue by Raph33** [padloc/padloc#262]
Current behavior:
- User is in Vault X
- User creates New Item 1
- New Item 1 is placed in "My Vault" by default (user can change that when creating the item, but if doing it quickly, they will likely overlook this)

What I think should be a better behavior:
- User is in Vault X
- User creates New Item 1
- New Item 1 is placed in "Vault X" by default (user can change it if needed when creating the item)

**Comment by MaKleSoft** [comment]
Makes sense! We'll consider this for the next release.
