### ISSUE TITLE
Official Padlock images on Docker Hub

### ISSUE THREAD

**Issue by dionysiusmarquis** [padloc/padloc#263]
Hey,

will there be official Padlock images in Docker Hub for self-hosting again? It's still critical to me to self-host the passwords.

**Comment by MaKleSoft** [comment]
Yes, absolutely. There is https://hub.docker.com/repository/docker/padloc/pwa and https://hub.docker.com/repository/docker/padloc/server, although they still need some documentation. Closing this as a duplicate of https://github.com/padloc/padloc/issues/254

**Comment by dionysiusmarquis** [comment]
Ah! I was searching for `padlock` all the time. I just dindn't realize the name changed :stuck_out_tongue:

**Comment by mpfaff** [comment]
FYI, the provided links take me to a login page. The correct ones are https://hub.docker.com/r/padloc/pwa and https://hub.docker.com/r/padloc/server
