### ISSUE TITLE
Problem running "npm run pwa:start"

### ISSUE THREAD

**Issue by tessierp** [padloc/padloc#269]
Environment variables set, get the follow error :

lerna ERR! npm run start exited 1 in '@padloc/pwa'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! padloc@3.0.10 pwa:start: `lerna run start --scope @padloc/pwa`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the padloc@3.0.10 pwa:start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tessierp\AppData\Roaming\npm-cache\_logs\2020-01-17T15_20_31_082Z-debug.log

Log file :

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'pwa:start'
1 verbose cli ]
2 info using npm@6.11.3
3 info using node@v12.12.0
4 verbose run-script [ 'prepwa:start', 'pwa:start', 'postpwa:start' ]
5 info lifecycle padloc@3.0.10~prepwa:start: padloc@3.0.10
6 info lifecycle padloc@3.0.10~pwa:start: padloc@3.0.10
7 verbose lifecycle padloc@3.0.10~pwa:start: unsafe-perm in lifecycle true
8 verbose lifecycle padloc@3.0.10~pwa:start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Development\Prototypes\Tests\padlock\padloc\node_modules\.bin;c:\program files\powershell\6;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\Python27\;C:\Python27\Scripts;C:\Program Files\Microsoft MPI\Bin\;C:\Oracle\11.2.0\bin;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\PowerShell\6\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;;C:\Program Files\LINQPad6;C:\Program Files\PuTTY\;C:\WINDOWS\System32\OpenSSH\;C:\Users\tessierp\AppData\Local\Microsoft\WindowsApps;C:\Users\tessierp\AppData\Roaming\npm;C:\Users\tessierp\.dotnet\tools;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps
9 verbose lifecycle padloc@3.0.10~pwa:start: CWD: C:\Development\Prototypes\Tests\padlock\padloc
10 silly lifecycle padloc@3.0.10~pwa:start: Args: [ '/d /s /c', 'lerna run start --scope @padloc/pwa' ]
11 silly lifecycle padloc@3.0.10~pwa:start: Returned: code: 1  signal: null
12 info lifecycle padloc@3.0.10~pwa:start: Failed to exec pwa:start script
13 verbose stack Error: padloc@3.0.10 pwa:start: `lerna run start --scope @padloc/pwa`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid padloc@3.0.10
15 verbose cwd C:\Development\Prototypes\Tests\padlock\padloc
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "pwa:start"
18 verbose node v12.12.0
19 verbose npm  v6.11.3
20 error code ELIFECYCLE
21 error errno 1
22 error padloc@3.0.10 pwa:start: `lerna run start --scope @padloc/pwa`
22 error Exit status 1
23 error Failed at the padloc@3.0.10 pwa:start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by MaKleSoft** [comment]
Did you run `npm install` and `npm run pwa:build` first?

**Comment by MaKleSoft** [comment]
Closing because no feedback from author.
