### ISSUE TITLE
Limit account creation

### ISSUE THREAD

**Issue by luxaritas** [padloc/padloc#270]
Been looking around again to see if there was a good open source password manager to use for an organization, and padloc looks nice! However, there's one thing I'd like to propose for this use case: limiting account creation. I'd like to be able to set it up so that only "global admin users" can invite new users by email, instead of any user being able to register.

**Comment by MaKleSoft** [comment]
Good point! An email whitelist should solve this problem, no? That's been on our todo-list anyway.

**Comment by luxaritas** [comment]
Depends on what you mean by whitelist - domain whitelisting would be helpful for some but not in my case. If it's a difference between "invite someone by email" vs "allow someone by email", I don't particularly care. Or am I missing what you're suggesting would be different?

**Comment by MaKleSoft** [comment]
Whitelisting could work for specific email addresses as well as wildcard-based patterns. So yes, allowing specific people would definitely work. Additionally, we may consider a preference for only allowing users to sign up if they have an existing invite to an organization, which is probably close to what you have in mind.

**Comment by mpfaff** [comment]
Any update on this? Or a quick 'n dirty workaround?

**Comment by MaKleSoft** [comment]
@mpfaff No news on this yet, sorry. We'll tackle this and other self-hosting related issues after the next minor release.

**Comment by mpfaff** [comment]
I've ended up modifying my copy of the source code to set the allowed domain as a regex via an environment variable. I was just trying to get something that worked, so it isn't the prettiest solution, but it works.

**Comment by brightcolor** [comment]
@mpfaff can pls you explain how you did it?

**Comment by iwkse** [comment]
Hi, interested in that as well..so for now there's nothing yet added but only a workaround?

**Comment by MaKleSoft** [comment]
@iwkse No, this has not been added yet, although it is on the To-Do list :)

**Comment by mpfaff** [comment]
@brightcolor I just used basic JavaScript regex capabilities and got the regex from an environment variable. I can go dig up my changes if you'd like, but I've moved to using https://github.com/dani-garcia/bitwarden_rs instead.

**Comment by MaKleSoft** [comment]
This should be solved by the provisioning functionality in v4 (not yet documented, but will be soon).
