### ISSUE TITLE
Failed to generate master password

### ISSUE THREAD

**Issue by larshg** [padloc/padloc#272]
I get the following error:

```
Uncaught (in promise) TypeError: Cannot read property 'generateKey' of undefined
    at WebCryptoProvider.generateKey (crypto.ts:43)
    at Account.initialize (account.ts:116)
    at App.signup (app.ts:554)
    at HTMLElement._submitPassword (signup.ts:434)
    at HTMLElement.<anonymous> (signup.ts:358)
    at EventPart.handleEvent (parts.js:419)
    at HTMLElement.EventPart._boundHandleEvent (parts.js:385)
```

I read somewhere that it is not hosted on https - could that be the case?

**Comment by MaKleSoft** [comment]
Yes, for the webcrypto api to be available the site has to be served via https. I'm assuming that is not the case here?

**Comment by larshg** [comment]
Nope, yet another thing I have to look into. I followed the steps in the readme, but there is nothing about https.

**Comment by larshg** [comment]
I have tried copying the dist of the web app to and IIS host with lets encrypt ssl and it seems to work.

But how exactly do I get the server part build? That I can't figure...

**Comment by MaKleSoft** [comment]
> But how exactly do I get the server part build? That I can't figure...

Not sure what you mean by that?

**Comment by larshg** [comment]
Yeah, I guess I'm too used to Visual studio projects and want to build everything :)

The server project just need to be run from node.js? Thats my current attempt and then use IIS as a reverse proxy to node.js.

Else I'm not sure how to get the node.js under SSL.

I'm not that familiar with linux systems, but I maybe nginx can do something similar here?

**Comment by larshg** [comment]
When I try to launch it in cmd prompt it doesn't find any project after "filtering".

I noticed that there are both ' and " in the filter on my windows machine, but not on my virtual linux.

![image](https://user-images.githubusercontent.com/1165340/75654650-7e12d280-5c60-11ea-9b5c-b8acffbadbee.png)

Got any idea where I can remove that?

**Comment by larshg** [comment]
Woa :)

I have it more or less runing now, with a mixture of letting the pwa running directly in IIS.

Having IIS work as reverse proxy to the server part.

Hardcode values instead of using the enviroment variables as they didn't work properly on windows.  [Cross-Env](https://www.npmjs.com/package/cross-env) package could maybe help with this.

**Comment by larshg** [comment]
Closing this, as the original question was solved using https.

**Comment by MaKleSoft** [comment]
@larshg Thanks for the follow-up! The whole https issue is definitely something that should be documented better.
