### ISSUE TITLE
Linux app fails to start: FATAL:setuid_sandbox_host.cc

### ISSUE THREAD

**Issue by suihkulokki** [padloc/padloc#275]
With padlock 2.7, it was just possible to download the .appimage, chmod a+x it, and run. With padloc 3, startup errors out:
```
> Padloc-3.0.14.AppImage &
> [10902:0413/185608.734314:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_Padloc2aPqek/chrome-sandbox is owned by root and has mode 4755.
fish: “Padloc-3.0.14.AppImage &” terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by suihkulokki** [comment]
Turns out this is a common electron problem, and there are essentially 3 solutions to choose from:

https://medium.com/@authmane512/solve-the-suid-sandbox-helper-binary-was-found-but-is-not-configured-correctly-3-solutions-4f1425a9a76c

**Comment by MaKleSoft** [comment]
Closing this as I don't see what we can do to mitigate this at our end. @suihkulokki Thanks for doing the research on potential workarounds!
