### ISSUE TITLE
Docker Build/Run Environmental Variable Problem

### ISSUE THREAD

**Issue by swrap** [padloc/padloc#278]
# Issue
Ran into a problem with the [docker-compose](https://github.com/padloc/padloc/blob/master/docker-compose.yml) file is that it uses the Dockerfile shares the same environmental variable names as the webpack.

# Example

## Assumption
Lets assume we have the following environmental variable set:
```
PL_SERVER_URL=8000
```
## Explanation
In the [packages/pwa/webpack.config.js](https://github.com/padloc/padloc/blob/master/packages/pwa/webpack.config.js) the following is used for the server url
```
...
const serverUrl = process.env.PL_SERVER_URL || `http://0.0.0.0:${process.env.PL_SERVER_PORT || 3000}`;
...
```
This causes the `PL_SERVER_PORT` to be hard-coded during the `docker build` process for each of the pieces of the padloc app.

Then in the (docker-compose)[https://github.com/padloc/padloc/blob/master/docker-compose.yml] file there is a mapping for the ports:
```
...
        ports:
            - $PL_SERVER_PORT:3000
...
```
The port `8000` gets mapped to port `3000`, however during the `docker build` we have port `8000` hard coded into the source code. This means that docker maps `8000->3000`, but the server is running in the docker container on port `8000`. Therefore it will not work.

# Remedy

## Short Term
- During your docker build make sure no environmental variables are set.
  - Pros
    - Easy to do
 - Cons
    - If you forget than you will a lot of problems
    - Cumbersome for automatic builds if you want to set it a custom port just for the docker container
## Long Term
1. Change the environmental variable for the docker build.
 - Pros
    - Keeps local npm run separate from docker environmental variables
2. Change the `docker-compose` file to map `PL_SERVER_PORT:PL_SERVER_PORT`
 - Pros
    - Easy to understand and will map accordingly for `docker build`
 - Cons
    - Must keep the environmental variable consistent
3. Others... I can't think of right now. Open to suggestions!

**Comment by MaKleSoft** [comment]
I think this should no longer be  a problem with the setup described here: https://padloc.app/help/guides/self-host/
@swrap What do you think?

**Comment by swrap** [comment]
Thanks yes I saw the setup from the other ticket. Still running into some problems when I run it with the following `.env` file:
```
PL_SERVER_PORT=3001
PL_BILLING_PORT=4001
PL_PWA_PORT=8081
```

I can access the app via `localhost:8081`, however app is not contacting the correct port for the server:

![image](https://user-images.githubusercontent.com/8915311/90338088-143f7880-dfb5-11ea-9b8f-c561a93e427e.png)

Again I believe the problem with the same name for environmental variables may be a problem, but I haven't tested that.

**Comment by MaKleSoft** [comment]
@swrap It looks like you haven't set the `PL_SERVER_URL` variable (that's what tells the PWA where to reach the server)? Note that if you're exposing the server on a port other than 80/443, you'll need to add the port to the url. So in your case that would be:
```sh
PL_SERVER_URL=http://localhost:3001/
```

**Comment by swrap** [comment]
That seemed to do it! However, from a usability standpoint I think it should have worked even without setting the `PL_SERVER_URL`?

**Comment by MaKleSoft** [comment]
Hm, I guess we could default `PL_SERVER_URL` to `https://localhosts:$PL_SERVER_PORT`.

Can you try making the following change to your `docker-compose.yml` and unsetting `PL_SERVER_URL` and see if it still works?

```diff
    pwa:
        image: padloc/pwa
        container_name: padloc_pwa
        ports:
            - ${PL_PWA_PORT:-8080}:8080
        volumes:
            - ${PL_PWA_DIR:-./pwa}:/pwa
        environment:
-           - PL_SERVER_URL
+           - PL_SERVER_URL=http://localhost:${PL_SERVER_PORT:-3000}/
```

**Comment by swrap** [comment]
LGTM, I would just make it a bit more simple b/c `PL_SERVER_PORT` is already required:
```diff
    pwa:
        image: padloc/pwa
        container_name: padloc_pwa
        ports:
            - ${PL_PWA_PORT:-8080}:8080
        volumes:
            - ${PL_PWA_DIR:-./pwa}:/pwa
        environment:
-           - PL_SERVER_URL
+           - PL_SERVER_URL=http://localhost:$PL_SERVER_PORT/
```

**Comment by MaKleSoft** [comment]
> I would just make it a bit more simple b/c PL_SERVER_PORT is already required

It isn't actually, since `PL_SERVER_PORT` defaults to `3000`.

**Comment by swrap** [comment]
That might be true at the application level, but as far as the `docker-compose` files is concerned, it will fail without it.

Try running `docker-compose up -d` with a clean shell and no `.env` file, it errors out:
```
$ docker-compose.exe up -d
WARNING: The PL_SERVER_PORT variable is not set. Defaulting to a blank string. 
WARNING: The PL_BILLING_PORT variable is not set. Defaulting to a blank string.
WARNING: The PL_PWA_PORT variable is not set. Defaulting to a blank string.    
ERROR: The Compose file '.\docker-compose.yml' is invalid because:
services.server.ports contains an invalid type, it should be a number, or an object
services.server.ports contains an invalid type, it should be a number, or an object
services.pwa.ports contains an invalid type, it should be a number, or an object   
```

Thats what I meant by required.

**Comment by MaKleSoft** [comment]
Are you using the `docker-compose.yml` from the guide? Because that one should work without the port set explicitly:

```sh
version: "3"
services:
    server:
        image: padloc/server
        container_name: padloc_server
        ports:
            - ${PL_SERVER_PORT:-3000}:3000 # <= Defaults to 3000 if PL_SERVER_PORT is not set
        volumes:
            - ${PL_DB_DIR:-./db}:/data
            - ${PL_ATTACHMENTS_DIR:-./attachments}:/docs
        environment:
            - PL_PWA_URL
            - PL_EMAIL_SERVER
            - PL_EMAIL_PORT
            - PL_EMAIL_USER
            - PL_EMAIL_PASSWORD
            - PL_EMAIL_FROM
    pwa:
        image: padloc/pwa
        container_name: padloc_pwa
        ports:
            - ${PL_PWA_PORT:-8080}:8080
        volumes:
            - ${PL_PWA_DIR:-./pwa}:/pwa
        environment:
            - PL_SERVER_URL
```

**Comment by swrap** [comment]
Oh yeh, definitely using the wrong `docker-compose.yml`. I just cloned the repo and started this sucker up. Your fix is good! Thanks for the help!

**Comment by MaKleSoft** [comment]
Please note that your setup will only work on your local environment. As soon as you deploy the setup to a server, you won't get around setting the `PL_SERVER_URL` variable since the docker doesn't know which domain/ip the host is at.

Also I just realised that [my previous suggestion](https://github.com/padloc/padloc/issues/278#issuecomment-674545447) is no good because this would prevent the variable to be set from the `.env` file, so we'll leave that as-is.

Closing this now since the original issue seems to be resolved. If you have any more feedback about the guide, please post it over at https://github.com/padloc/padloc/issues/254
