### ISSUE TITLE
New item has fields filled from last created item

### ISSUE THREAD

**Issue by Raph33** [padloc/padloc#280]
This is what happens:
1. I create item A, filling a few fields
2. I save item A
3. Later, I create item B
4. Item B has the fields filled in item A already filled, with the same value as item A (including password!!)

**Comment by Raph33** [comment]
@MaKleSoft I take it that this was fixed?  When do you expect to release the fix?

**Comment by MaKleSoft** [comment]
@Raph33 Yes, this is fixed. Next release is scheduled for the weekend.
