### ISSUE TITLE
Clicking on sign up fails with a status of 431 (Request Header Fields Too Large)

### ISSUE THREAD

**Issue by iwkse** [padloc/padloc#284]
Hi,
I'm having an issue with padloc and having that only on a centos server (node 12.8.0)

When I run it on a local machine, without settiing PL_SERVER_URL and PL_PWA_URL it works as expected.

On the server, when I leave such variables unset, I see the red error, "offline"

If I'm going to set PL_SERVER_URL and PL_PWA_URL it seems to work properly but when I'm going to sign up I get a 431.

Any hints?

**Comment by MaKleSoft** [comment]
Hm, that's new. Can you post the output from the network tab in your browser? Are you exposing the two services directly or behind a reverse proxy?

**Comment by iwkse** [comment]
Hi,
Will be sending soon with details. Services are run directly and I notice this also happen if I'm running padloc on a machine and I try to access from another local LAN machine to it.

**Comment by iwkse** [comment]
Hi, actually I got it working...just using the server IP address on PL_SERVER_URL and PL_PWA_URL instead of the domain name.

**Comment by iwkse** [comment]
Hi again, can't create the account now. Console log shows:
```
crypto.ts:43 Uncaught (in promise) TypeError: Cannot read property 'generateKey' of undefined
    at WebCryptoProvider.generateKey (crypto.ts:43)
    at Account.initialize (account.ts:144)
    at App.signup (app.ts:586)
    at HTMLElement._submitPassword (signup.ts:460)
    at HTMLElement.<anonymous> (signup.ts:359)
    at EventPart.handleEvent (parts.js:419)
    at HTMLElement.EventPart._boundHandleEvent (parts.js:385)
```
I'm not using SSL as this is not exposed on the web

**Comment by MaKleSoft** [comment]
The client app requires the webcrypto api which is only available in a secure context. So I'm afraid you won't get around setting up a secure connection. Have you tried following our [Self-Hosting Guide](https://padloc.app/help/guides/self-host/)?

**Comment by iwkse** [comment]
Thanks, so I'm going to go with SSL

**Comment by iwkse** [comment]
I've set a reverse proxy and I got SSL working.
But still some issues when trying to login.
```
Failed to load resource: the server responded with a status of 405 ()
2
ajax.ts:58 Uncaught (in promise) Error
    at AjaxSender.send (ajax.ts:58)
    at async Client.call (client.ts:78)
    at async App.loadBillingProvider (app.ts:1779)
x.x.x.x:3000:1 Failed to load resource: the server responded with a status of 405 ()
2
ajax.ts:58 Uncaught (in promise) Error
    at AjaxSender.send (ajax.ts:58)
    at async Client.call (client.ts:78)
    at async App.login (app.ts:618)
    at async HTMLElement._submit (login.ts:197)
login:1 Failed to load resource: the server responded with a status of 404 ()
```
