### ISSUE TITLE
Added APK to release

### ISSUE THREAD

**Issue by MalteKiefer** [padloc/padloc#292]
Hello,

is it possible to add an APK file to the releases?
I don't use Google Play Store, and so I can use your software without building it on every update.
Thanks.

**Comment by MalteKiefer** [comment]
@MaKleSoft any news on this?

**Comment by MaKleSoft** [comment]
@MalteKiefer Sorry for not responding sooner. I don't know a lot about side-loading Android apps but I assume there is no difference in how the apk is build/signed. I've uploaded an apk file to the [latest release](https://github.com/padloc/padloc/releases/tag/v3.1.3). Let me know if that build works for you and I'll make sure we'll be distributing then standalone apk with every release from now on.
