### ISSUE TITLE
Uncaught (in promise) Error: ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by dome4** [padloc/padloc#297]
The following error occurs in the pwa when starting the server via `npm run start` as suggested in the readme.

```
Uncaught (in promise) Error: ReferenceError: TextEncoder is not defined
    at Client.call (client.ts:88)
    at async App.login (app.ts:637)
    at async App.recoverAccount (app.ts:829)
```

version: commit https://github.com/padloc/padloc/commit/6df131ae692dc768464837c9de8b83ea49c3297c
browser: checked on firefox and chromium

**Comment by MaKleSoft** [comment]
Hm, what Firefox/Chromium versions are you running? TextEncoder is a somewhat new standard but should be supported by all modern browsers: https://caniuse.com/textencoder

**Comment by dome4** [comment]
I figured out that it seems to be an issue with node 10: https://github.com/heineiuo/rippledb/issues/148. Thus using node 12 as described in the readme should fix the problem.
