### ISSUE TITLE
Auto-Lock does not work in Chrome Extension

### ISSUE THREAD

**Issue by MaKleSoft** [padloc/padloc#300]

**Comment by BrunoBernardino** [comment]
It seems that [`setTimeout` just doesn't work past 10 seconds on chrome extensions](https://stackoverflow.com/questions/26539801/chrome-extension-settimeout-not-working-properly). We need to use the [alarms API](https://developer.chrome.com/docs/extensions/reference/alarms/) in https://github.com/padloc/padloc/blob/v4/packages/app/src/mixins/auto-lock.ts#L67 when running in chrome.

**Comment by MaKleSoft** [comment]
Actually the code you pointed to is not really relevant for the extension since it only runs in the popup and that loses state every time you close it, anyway. The popup actually has to grab the master key from the background script to avoid having to unlock the app every single time: https://github.com/padloc/padloc/blob/master/packages/extension/src/app.ts#L37

So auto lock functionality for the extension would actually have to be implemented in the [background script](https://github.com/padloc/padloc/blob/master/packages/extension/src/background.ts), which is the one holding onto the master key. Your point about `setTimeout` is still valid in that context though.
