### ISSUE TITLE
Why Premium?

### ISSUE THREAD

**Issue by dragonBall561** [padloc/padloc#301]
Look, if this software is open-source, it shouldn't have a premium option. Everything should be free BECAUSE THAT IS WHAT OPEN SOURCE IS!! 

I am surprised that no one else said something about this!!

**Comment by MaKleSoft** [comment]
> Everything should be free BECAUSE THAT IS WHAT OPEN SOURCE IS!!

If that's what you think then you have not understood the spirit of open source. OSS is about openness, transparency and freedom of information, not "free stuff".

Open source projects, just like any other project, take a tremendous effort (and yes, money!) to develop, support and maintain. Who do you think pays for the servers, licenses and literally thousands of man-hours that went into this project?

It's this freebee culture that makes it so hard for open source projects to build an ethical, sustainable business to support their work while people giddily download free apps that steal and sell their personal data without so much as a shrug.

Having said that, if you don't like the limitations that come with the free plan, you always have the option to simply host your own Padloc instance _for free_, as long as you adhere to the terms of the projects license. A detailed guide on how to do can be found here: https://padloc.app/help/guides/self-host/

Closing this as off-topic. If you have an actual contribution in form of a technical question, bug report or feature request, please open a new ticket.
