### ISSUE TITLE
Importing encrypted backup fails 

### ISSUE THREAD

**Issue by nopslip** [padloc/padloc#303]
I'm trying to import an encrypted back up and while it says that the import is successful and doesn't kick off an error, this is the only item that gets imported (backup has 166 items):

<img width="435" alt="Screen Shot 2021-02-24 at 2 52 42 PM" src="https://user-images.githubusercontent.com/1734015/109070885-50fcd280-76b0-11eb-8141-ef527780b990.png">

I thought maybe the pbes2 file was corrupt so I tried creating a new vault with a new saved item and exported that (encrypted). Then I created another new vault and tried to import the freshly created backup and it still gives the same result (screen shot above).  

I wasn't able to find any existing issues related to importing backups. Maybe i'm just missing something?

Details: 
Padloc V3.1.3
Mac OS Big Sur V11.1 (I also tried Debian and the web UI too)

**Comment by MaKleSoft** [comment]
Should be fixed in v3.1.4. @nopslip Can you verify you can now import using the web app (web.padloc.app)? (the version has not been released to other platforms yet) Once you've verified the fix we'll release to the other platforms as well.

**Comment by nopslip** [comment]
Excellent. That worked without issue on the new web V3.1.4. Thank you!
