### ISSUE TITLE
Avoid double slashes when generating urls

### ISSUE THREAD

**Issue by kakalpa** [padloc/padloc#310]
Hi, 

I have a selfhosted padloc which runs on a local ip. every thing is working fine the invites are also working for new users but when it comes to invites for the existing users when clicked on the invite link they are asked to log in after login in nothings changed. no confirmation codes asked no nothing

**Comment by BlackMark29A** [comment]
I ran into this same issue and managed to solve it, at least for my setup.

The self hosting instructions show a trailing slash for the URL environment variables, however this causes some links (specifically the invite link) to be generated with two consecutive slashes, which breaks the functionality.

Changing the config to not have trailing slashes has solved this issue for me:

```diff
 # URL that will resolve to the server instance
-PL_PWA_URL=https://example.com/
+PL_PWA_URL=https://example.com
 # URL that will resolve to the web app
-PL_SERVER_URL=https://example.com/server/
+PL_SERVER_URL=https://example.com/server
```

**Comment by MaKleSoft** [comment]
@BlackMark29A Great catch! So this should be easy to fix by avoiding double slashes when generating urls. I'll rename the issue accordingly.
