### ISSUE TITLE
How to import early version `padlock` back up data?

### ISSUE THREAD

**Issue by kobeHub** [padloc/padloc#316]
I used `padlock` to export a JSON format file as backups, but I can't find a early version `packlock` android app now. How can I import a JSON file in `padloc` now? 
Thanks in advance!

**Comment by MaKleSoft** [comment]
@kobeHub You should be able to import older Padloc export files into the new version without problems. Have you tried simply [importing](https://padloc.app/help/manual/import/#from-padloc-export) it?

**Comment by kobeHub** [comment]
I tried, but nothing happened.
I found there are different formats between Padloc and Padlock exported files.
The exported file format of Padloc:
```json
{
    "encryptionParams": {
        "algorithm": "AES-GCM",
        "tagSize": 128,
        "keySize": 256,
        "iv": "#####",
        "additionalData": "####",
        "kind": "aesencryptionparams",
        "version": "3.1.0"
    },
    "keyParams": {
        "algorithm": "PBKDF2",
        "hash": "SHA-256",
        "keySize": 256,
        "iterations": 50000,
        "salt": "###",
        "kind": "pbkdf2params",
        "version": "3.1.0"
    },
    "encryptedData": "###",
    "kind": "pbes2container",
    "version": "3.1.0"
}
```
And my Padlock exporting:
```json
{
    "cipher": "AES",
    "mode": "ccm",
    "iv": "###",
    "salt": "###",
    "keySize": 256,
    "iter": 1000,
    "ct": "###",
    "adata": "###",
    "ts": 64
}
```

**Comment by MaKleSoft** [comment]
Yes, the format has changed, but Padloc 3 should nevertheless be able to import it. So when you say nothing happens, does that mean you are able to select the file and enter the password, but no data is being imported?

**Comment by kobeHub** [comment]
I got it! The file isn't named with `.json`  suffix, so I cannot import it. 
Thank you very much!

**Comment by MaKleSoft** [comment]
@kobeHub Sorry for ghosting you on this! I'm going to close this now since it's a few months old and I'm assuming you've either solved the problem or given up. Feel free to reopen if this is still relevant.
