### ISSUE TITLE
Menu Popovers on buttons close to the viewport edge get cut off

### ISSUE THREAD

**Issue by BrunoBernardino** [padloc/padloc#349]
I can't take a screenshot of the app on my phone, but when you edit an item and then press the ellipsis on the top right to see "Move To Vault" and "Delete Item", the menu is cutoff and you can only see the first 7-8 letters.

This is on a Fairphone 3, running /e/OS 0.19 (based off of Android 10).

Here's the affected code: https://github.com/padloc/padloc/blob/v4/packages/app/src/elements/item-view.ts#L327-L343

**Comment by MaKleSoft** [comment]
Looks like this happens on all popovers that are too close to the edge. Renaming the issue accordingly
<img width="361" alt="Screenshot 2021-12-24 at 10 53 05" src="https://user-images.githubusercontent.com/1270940/147342230-1f57fe6d-8698-495c-8d25-b1ed69154ddf.png">
.

**Comment by MaKleSoft** [comment]
Fixed by https://github.com/padloc/padloc/pull/382
