### ISSUE TITLE
Renaming a Vault doesn't update the sidebar

### ISSUE THREAD

**Issue by BrunoBernardino** [padloc/padloc#350]
I created a shared vault and then renamed it. If I reload the app, it shows the new name on the sidebar, but there's no easy way to "reload" the extension, which means I see the right name when I'm in the organization's setting, but not on the left side. Even closing and opening the extension doesn't fix it.

Other clients/apps open, reload and properly show the updated vault name.

I suppose this is a bigger problem for the extension since it's not as easy to reload it.

**Comment by MaKleSoft** [comment]
Actually, the extension get's reloaded every time you open the popup. The name in the side bar should get updated as soon as the next sync finishes. This happens automatically once per minute, but you can manually trigger a sync by clicking the sync button in the footer of the menu. Can you check if manually triggering a sync updates the vault name in the side bar?

**Comment by BrunoBernardino** [comment]
I tried manually triggering a sync but that didn't update. The only thing that worked was closing and re-opening the browser. I also had the popup/extension open for at least a couple of minutes as I was trying it on another computer, and it didn't fix it.

**Comment by MaKleSoft** [comment]
Alright, let me try to reproduce this.

**Comment by BrunoBernardino** [comment]
This had https://github.com/padloc/padloc/issues/427 as a duplicate and was fixed already.
