### ISSUE TITLE
Fix „add to home screen“ icon on iOS

### ISSUE THREAD

**Issue by MaKleSoft** [padloc/padloc#359]
![E45C59B1-8520-4FF6-B630-CAAD04007533](https://user-images.githubusercontent.com/1270940/147406976-12db86c5-c19d-4963-beee-1d55dc44243d.jpeg)

**Comment by BrunoBernardino** [comment]
@MaKleSoft are you still seeing this? I don't have an iOS device handy right now to try and reproduce, but all I've seen in the source code and deployed in beta and current v3 seems fine and should work.

**Comment by MaKleSoft** [comment]
Can't reproduce this now, actually. It's possible we inadvertently fixed this when working on the whole build process. The icon has a black background and the spacing isn't right, but I'm not sure if it's worth investing the time to make it look better at this point.

![IMG_53747106C28B-1](https://user-images.githubusercontent.com/1270940/154499568-c0d650a9-d2b9-4937-822f-ea79993d3653.jpeg)

**Comment by BrunoBernardino** [comment]
Indeed, I also just tried it on and it's working, with the same "UI issues".
