### ISSUE TITLE
[Tauri] Add application menu

### ISSUE THREAD

**Issue by MaKleSoft** [padloc/padloc#364]
At a minimum this should include the same items as the electron version:
<img width="328" alt="Screenshot 2021-12-29 at 09 49 08" src="https://user-images.githubusercontent.com/1270940/147643938-64d838e1-fcb5-4765-9e37-5647aa3bf839.png">
<img width="222" alt="Screenshot 2021-12-29 at 09 49 24" src="https://user-images.githubusercontent.com/1270940/147643963-e8734e8e-51c1-402a-96ad-015682d86d5d.png">

With @probablykasper's permission, maybe we can just copy it from their template: https://github.com/probablykasper/tauri-template/blob/14b51d4f8702f5fdcb54cf528bdbf3be61e36372/src-tauri/src/main.rs#L47

See also: https://tauri.studio/en/docs/usage/guides/visual/menu/

**Comment by probablykasper** [comment]
If you're on the next branch, I highly recommend specifying the menu like this - You'll need to use `#[cfg]` attributes, which are way 10x nicer to deal with this way.
```rust
.menu(Menu::with_items([
  #[cfg(target_os = "macos")]
  MenuEntry::Submenu(Submenu::new(
    &ctx.package_info().name,
    Menu::with_items([
      MenuItem::About(ctx.package_info().name.clone()).into(),
      MenuItem::Separator.into(),
      MenuItem::Services.into(),
      MenuItem::Separator.into(),
      MenuItem::Hide.into(),
      MenuItem::HideOthers.into(),
      MenuItem::ShowAll.into(),
      MenuItem::Separator.into(),
      MenuItem::Quit.into(),
    ]),
  )),
  MenuEntry::Submenu(Submenu::new(
    "File",
    Menu::with_items([
      MenuItem::CloseWindow.into(),
    ]),
  )),
  MenuEntry::Submenu(Submenu::new(
    "Edit",
    Menu::with_items([
      MenuItem::Undo.into(),
      MenuItem::Redo.into(),
      MenuItem::Separator.into(),
      MenuItem::Cut.into(),
      MenuItem::Copy.into(),
      MenuItem::Paste.into(),
      #[cfg(not(target_os = "macos"))]
      MenuItem::Separator.into(),
      MenuItem::SelectAll.into(),
    ]),
  )),
  MenuEntry::Submenu(Submenu::new(
    "View",
    Menu::with_items([MenuItem::EnterFullScreen.into()]),
  )),
  MenuEntry::Submenu(Submenu::new(
    "Window",
    Menu::with_items([MenuItem::Minimize.into(), MenuItem::Zoom.into()]),
  )),
  // You should always have a Help menu on macOS, since It will automatically shows a search field
  MenuEntry::Submenu(Submenu::new(
    "Help",
    Menu::with_items([CustomMenuItem::new("Learn More", "Learn More").into()]),
  )),
]))
```

**Comment by MaKleSoft** [comment]
@probablykasper Thanks for the input! We're currently on the latest beta release so we probably can't use that yet. The code from your template works like a charm though 😊
