### ISSUE TITLE
Crashing because of Encoding Error

### ISSUE THREAD

**Issue by falsaffa** [padloc/padloc#381]
**Summary**

Padloc on linux Ubuntu 20.04 crashes periodically (between 1 hour and 6 hours apart) because of the following error:

```
lerna ERR! npm run start stderr:
 /opt/padloc/padloc/packages/core/src/encoding.ts:324
         throw new Err(ErrorCode.ENCODING_ERROR, e.toString());
               ^
 Err [Error]: SyntaxError: Unexpected token < in JSON at position 0
     at Object.unmarshal (/opt/padloc/padloc/packages/core/src/encoding.ts:324:15)
     at Server.<anonymous> (/opt/padloc/padloc/packages/server/src/http.ts:49:55)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
   time: 2022-01-11T16:34:18.802Z,
   code: 'encoding_error',
   report: false,
   display: false,
   originalError: undefined
}
```

**Comment by MaKleSoft** [comment]
Dang, sorry for not answering sooner... this totally slipped by me. This looks like something other than Padloc is trying to send requests to your server... Can you check your access logs to see what this might be? Regardless, the server definitely shouldn't be crashing when being sent malformed requests, so we'll have to look into this.

**Comment by falsaffa** [comment]
Thanks for reaching out!

Yeah it looks like I found some bots scouring the internet for `GET /.env` and some `POST /` data. I need to do some access control work. Good call!

But thanks for adding it to the milestone! Appreciate it
