### ISSUE TITLE
Moving an item to another vault puts the web extension in a "broken" state

### ISSUE THREAD

**Issue by BrunoBernardino** [padloc/padloc#391]
Basically the problem is that I'm shown an item that isn't available, so I can't get back or do anything.

To fix this, I have to open a tab with a URL for which I have items, and only then I can get back to "all items", fixing the problem in the original tab.. 

To reproduce:
- Create an item in "My Vault"
- Open the item
- Move it to another vault
- You should now see the problem

Ideally I should keep seeing the item, now in the new vault.

Note this happened in LibreWolf (Firefox), for Linux, but I imagine chrome will have the same problem.

FYI @MaKleSoft in case you know where this is already, otherwise I can try to fix this later.

**Comment by MaKleSoft** [comment]
Looks like a duplicate of https://github.com/padloc/padloc/issues/338, which should have been fixed with https://github.com/padloc/padloc/pull/389. Can you double-check that you're running the latest build?

**Comment by BrunoBernardino** [comment]
Good point. I don't have that, so I'm building it at https://github.com/padloc/padloc/actions/runs/1729733401 and will then try it out.

**Comment by BrunoBernardino** [comment]
Yeah, I can confirm it's working with that PR.
