### ISSUE TITLE
Integration/Sync With Directory Services

### ISSUE THREAD

**Issue by MaKleSoft** [padloc/padloc#424]
**Groundwork and features:**

- [x] Develop core model and logic for "linking" directory services or identity providers with organisations
- [x] Automatically provision/onboard organisation members from upstream users
- [x] Sync upstream teams/groups with Padloc groups
- [ ] ~Sync upstream equivalent of vaults?~
- [ ] ~Sync upstream equivalent of vault permissions?~
- [ ] ~Use SSO~

**Planned Integrations:**

- [x] Integration/Sync with Active Directory (On-Premise)
- [x] Integration/Sync with Azure Active Directory
- [x] Integration/Sync with Office 365
- [x] Integration/Sync with Google Workspace

**Thoughts:**

- Ultimately it would be nice to offer this for our "Business" plan, but priority is to get this working for on-premise / enterprise users.
- With the exception of On-Premise AD, all of the planned integrations support OpenID, so that would probably a good starting point. We should should probably also look into whether it's possible to add an OpenID bridge On-Premise AD, which would safe us a lot of work and time.

**Comment by MaKleSoft** [comment]
We ended up simply implementing [SCIM](http://www.simplecloud.info/) standard, which should be compatible with most directory providers (See https://github.com/padloc/padloc/pull/429).

**Comment by celevra** [comment]
we use Keycloak as an openid bride for our onprem active directory
real SSO with any openid provider like azure ad, keycloak and so on would be nice
