### ISSUE TITLE
Renaming a vault doesn't update it on the left menu

### ISSUE THREAD

**Issue by BrunoBernardino** [padloc/padloc#427]
I've created a couple of vaults with the same name (by mistake), and then renamed them, to make sure I wasn't deleting the wrong one.

I noticed that renaming them didn't have an effect on the menu in the left sidebar. Even after closing and opening again the web app, it remained with the old name. I had to open a new tab (private/incognito) to see the new names.

I did this on beta/v4 with Firefox (extension + web app).

/cc @MaKleSoft if you have any thoughts on where to look.

**Comment by MaKleSoft** [comment]
Fixed: https://github.com/padloc/padloc/pull/447
