### ISSUE TITLE
Store item change history, allow "rewinding"

### ISSUE THREAD

**Issue by MaKleSoft** [padloc/padloc#434]

**Comment by BrunoBernardino** [comment]
@MaKleSoft I gave this some thinking and I plan to start working on it tomorrow. Here's my "v1" suggestion:

1. Add a new `history[]` property to `VaultItem` with the old and new data (`name` and `fields`, not sure if anything else), plus date and `accountId` which made the changes.
2. Cap it to 10 entries.
3. Allow viewing and deleting entries individually (basic `field: value` list for now, later we can improve that UI), and rewinding to a given one, updating `item.history` accordingly.

Let me know your thoughts.

**Comment by BrunoBernardino** [comment]
> I don't think being able to delete history entries is necessary. Simply reviewing and restoring them should be enough. But if if it's easy to add / doesn't add a lot of clutter why not :)

It's simply privacy. If I make a change I don't want anyone to know about (a mistake, etc.), but the item's shared, I should be able to make that go away.

> What happens when you restore a point in the history? ... I think the best way would be to treat it as any other change so that it appears as another entry in the history and the original history item stays untouched (unless it get's pushed out of the cue)

That's what I was going at with "updating `item.history` accordingly." So we're on the same page.

> In addition to fields, I think history entries should include:

Ok.

> What do we do about attachments?

For now... nothing. For the future we can simply _not_ delete the file right away and store the change in `history`, deferring the deletion of the file only when it's dropped from the history array.

> We might want to make sure that the history only gets updated if anything has actually changed

Roger that.
