### ISSUE TITLE
no confirmation email is being sent

### ISSUE THREAD

**Issue by joossii** [padloc/padloc#438]
I have tried everything, google email, sendgrid, own domain email. No email is being sent. When i test the smtp it works, but when i put in the details in the .env file .... nothing. It says it send it, but ... nothing received. I can't check the log because once installed like said on padloc website selfhosting there is no log directory made ....

**Comment by MaKleSoft** [comment]
Closing in favor of https://github.com/padloc/padloc/discussions/439
