### ISSUE TITLE
Upgrade Lerna (or switch to NX)

### ISSUE THREAD

**Issue by MaKleSoft** [padloc/padloc#470]
Looks like Lerna has finally found a new maintainer: https://github.com/lerna/lerna/issues/3121

Not sure what the path forward is since afaiu [NX and Lerna](https://nx.dev/migration/lerna-and-nx) are supposed to solve pretty much the same things. Simply upgrading to Lerna 5 is probably the easiest, but me may also want to think about switching to NX altogether.

**Comment by BrunoBernardino** [comment]
I would posit we could live without either of those and just use [`npm workspaces`](https://docs.npmjs.com/cli/v8/using-npm/workspaces), and have one less complex dependency.

**Comment by MaKleSoft** [comment]
@BrunoBernardino Well yes, that would be even better! I'm not sure what the challenges would be though. I remember last time I tried npm workspaces it did have some shortcomings that prevented us from switching but I don't remember what those were. It certainly would be a bit more work than simply bumping the Lerna version though, I suspect.

**Comment by BrunoBernardino** [comment]
I'm happy to go with an easier route (just upgrading lerna) if you prefer to spend less time on this.
