### ISSUE TITLE
unhandled exception when creating an account (master key)

### ISSUE THREAD

**Issue by danielzzz** [padloc/padloc#472]
hi, 

I am using a docker installation.

when trying to create a new (first) account, after inputting the master password I am getting this error in the console:
```
crypto.ts:43 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'generateKey')
    at WebCryptoProvider.generateKey (crypto.ts:43:50)
    at Account.initialize (account.ts:144:63)
    at App.signup (app.ts:579:23)
    at Signup._submitPassword (signup.ts:460:23)
    at Signup.<anonymous> (signup.ts:359:45)
    at EventPart.handleEvent (parts.js:419:1)
    at EventPart._boundHandleEvent (parts.js:385:1)
    ```
    
    please advice, thanks a lot!
    dan

**Comment by BrunoBernardino** [comment]
Hi @danielzzz thanks for reporting this! It looks like [this issue](https://github.com/padloc/padloc/issues/272) (and [this one too](https://github.com/padloc/padloc/discussions/440#discussioncomment-2853587)) can you confirm if you're trying to access the app via http instead of https?

**Comment by danielzzz** [comment]
hi, thanks - It was using http. I had no keys configured. 

After I put it behind a nginx with ssl certs it did worked, so I guess this was the problem.

thanks anyway!
dan

**Comment by BrunoBernardino** [comment]
Thanks for confirming, @danielzzz !
