### ISSUE TITLE
Support Apple Silicon (arm64, M1/M2) for the Tauri/macOS desktop app

### ISSUE THREAD

**Issue by BrunoBernardino** [padloc/padloc#495]
This still has some issues and isn't possible via GitHub Actions, like reported in https://github.com/tauri-apps/tauri/issues/4242 and https://github.com/tauri-apps/tauri/issues/2286 and https://github.com/actions/virtual-environments/issues/2187. Requested by a customer via email.

**Comment by JonasKruckenberg** [comment]
Support for macOS aarch64 was possible even before this, but I now modified the GH actions workflow to build for aarch64 too.
