### ISSUE TITLE
After unlocking, web extension should automatically show matching items (if any)

### ISSUE THREAD

**Issue by MaKleSoft** [padloc/padloc#512]
Currently when you unlock the web extension, you're always taken to "All Items". Instead, you should be shown matching items for the current tab (if any).

**Comment by BrunoBernardino** [comment]
Have you seen this happen with Beta? I haven't _unless_ I've previously selected all items before. In that case I get taken there instead of matching items.

**Comment by BrunoBernardino** [comment]
@MaKleSoft is this not working for you? It's still working as expected for me.

**Comment by MaKleSoft** [comment]
Actually, it's working now. Closing :)
