### ISSUE TITLE
Add better device descriptions for Tauri apps

### ISSUE THREAD

**Issue by MaKleSoft** [padloc/padloc#517]
Currently the Tauri app shows up as "Edge on Windows" (or something similar, depending on the platform). We should try to get a better device description. For reference, here is how it's done for the Cordova apps:  https://github.com/padloc/padloc/blob/main/packages/cordova/src/platform.ts#L51

**Comment by escapedraccoon** [comment]
Maybe also allow for changing the description, making it easier to distinguish between different installations on the Tauri platform (additionally keeping the standard-setting in brackets* to avoid malicious access renaming their app to something familiar)?

*(or at least show it somewhere)

**Comment by MaKleSoft** [comment]
@escapedraccoon Not a bad idea! I'll create a new ticket for it, but I can't promise when (or if) we'll implement this. But if enough people ask for it we'll consider it.
