### ISSUE TITLE
Firefox extension version

### ISSUE THREAD

**Issue by AndreJorgeLopes** [padloc/padloc#525]
Just a quick request to add the last version of the firefox extension to the firefox addons shop. The current version from the firefox shop doesn't work anymore but the one from the releases tab works like a charm!

**Comment by BrunoBernardino** [comment]
Hi @AndreJorgeLopes thanks for reporting this. We're aware of the issue and trying to get Firefox to re-publish 4.0.0 (which was there for a couple of days).

FYI @MaKleSoft

**Comment by MaKleSoft** [comment]
Should be fixed now!
