### ISSUE TITLE
Display error with translation

### ISSUE THREAD

**Issue by detobel36** [padloc/padloc#543]
With translation, text is "bigger" and thus display is not correctly done:
![image](https://user-images.githubusercontent.com/5373615/183578011-783cbefb-2a46-443f-9408-a4679b298ea5.png)

**Comment by BrunoBernardino** [comment]
Thanks for reporting this, @detobel36 !

**Comment by matheusrizzati** [comment]
Can I work in this bug?

**Comment by BrunoBernardino** [comment]
Sure thing @matheusrizzati !

**Comment by BrunoBernardino** [comment]
@detobel36 can you share a bit more about this (where and with what browser/OS is this happening)? I've just tried to reproduce it but couldn't:

![Screenshot from 2022-09-07 10-42-50](https://user-images.githubusercontent.com/1239616/188847758-abcb7b9b-6fc2-418a-ba13-e723e357dddd.png)

**Comment by detobel36** [comment]
Heu... xD
Same, I don't succeed to reproduce again this bug 😕 😝 

I think this ticket could be closed, and if I succeed to reproduce, I will "reopen" it 😉
