### ISSUE TITLE
Hitting back button after editing item makes app go back into edit mode

### ISSUE THREAD

**Issue by HikaruIchijyo** [padloc/padloc#552]
Cant record video

Video is blank.

Reproducing step.

Click on add >> website/App >> add  required field click on save it save the data try to swipe back using gesture it edits the text when u swipe back again it asks data isnt saved at all. The problem is with swipe shouldnt swipe simply go back instead of editing manually clicking back button does go back.

Tried on app & web both same result

Device : Redmi Note 10s 
Android 12
Miui 13

**Comment by MaKleSoft** [comment]
Thanks for reporting this, @HikaruIchijyo 

> Video is blank.

Yes, the app disallows any kind of screen capture as a security measure. You *should* be able to record the web app though since Chrome doesn't have any such protections.

> Click on add >> website/App >> add required field click on save it save the data try to swipe back using gesture it edits the text when u swipe back again it asks data isnt saved at all. The problem is with swipe shouldnt swipe simply go back instead of editing manually clicking back button does go back.

I'm not very familiar with the UX on Android, so just so I understand: The swiping gesture you are talking about should perform the same way as the back/forward button in the browser, correct?

**Comment by HikaruIchijyo** [comment]
> I'm not very familiar with the UX on Android, so just so I understand: The swiping gesture you are talking about should perform the same way as the back/forward button in the browser, correct?
> 

https://user-images.githubusercontent.com/38470944/184073113-50cf6634-5015-4be3-97e6-e7b02060b7d0.mp4

Also some more suggestions for swiping back.

When u swipe back from settings it should go to home but currently it switches there

**Comment by MaKleSoft** [comment]
Ok, gotcha. Same thing happens when simply clicking the back button in the browser so it's a problem with routing in general, not the swipe gesture in particular. Renaming the issue accordingly.

**Comment by HikaruIchijyo** [comment]
> Ok, gotcha. Same thing happens when simply clicking the back button in the browser so it's a problem with routing in general, not the swipe gesture in particular. Renaming the issue accordingly.

👌👌👌
