### ISSUE TITLE
Biometric Unlock toggle still clickable even if device isn't supported

### ISSUE THREAD

**Issue by MaKleSoft** [padloc/padloc#554]
Currently the toggle button is still clickable even if biometric unlock isn't supported on the current device / runtime. The toggle should be disabled instead.

<img width="502" alt="Screenshot 2022-08-11 at 08 38 39" src="https://user-images.githubusercontent.com/1270940/184077273-d2ea1e47-f98f-4376-9475-4cb62623bec1.png">

**Comment by BrunoBernardino** [comment]
I've just confirmed that in Tauri you can't click on the toggle when disabled, but you can on Electron, at least.

**Comment by MaKleSoft** [comment]
> I've just confirmed that in Tauri you can't click on the toggle when disabled

To be clear, the bug is that you shouldn't be able to click it, but you can in the latest version (at least in MacOS). Probably a regression in `v4.0.2`. Can you confirm this is the case in `v4.0.2` for you, too?

**Comment by BrunoBernardino** [comment]
I can in electron in v4.0.1 and v4.0.2, but not Tauri for either, for Linux. I suppose it might be something WebKitGTK forces, then.
