### ISSUE TITLE
Cannot fine .env file when using Docker-compose.yml file

### ISSUE THREAD

**Issue by AmoghSaxena** [padloc/padloc#574]
Hi I want to Install Padloc  using Docker. But I am unable to get the .env file while performing `git clone` 

Also is there any proper documentation for launching it via docker ?

thank you.!

**Comment by BrunoBernardino** [comment]
Hi @AmoghSaxena the `.env` file should be created by you, and we provide a "full example" at https://github.com/padloc/padloc/blob/main/docs/examples/config/example.env

Note that you should still be able to simply run the app with no env file (defaults will be used).

As for documentation on using docker, you can find some at https://docs.padloc.app/guides/self-host/

Let me know if you need anything else!
