### ISSUE TITLE
Getting Error : ERR_TLS_CERT_ALTNAME_INVALID

### ISSUE THREAD

**Issue by AmoghSaxena** [padloc/padloc#576]
After configuring Email. 

I am unable to signup as it is not able to send email and showing error 
```
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: mail.axolites.com. is not in the cert's altnames: DNS:s483.bom7.mysecurecloudhost.com
```

But my other apps with same email configurations are working like charm

**Comment by BrunoBernardino** [comment]
Hi @AmoghSaxena this looks like a certificate error that we can do nothing about, I'm afraid. Have you checked with tools like https://www.sslchecker.com/sslchecker to see if your certificate passes everything?

The only alternative here would be to disable or not use SSL/TLS.

**Comment by MaKleSoft** [comment]
Closing this as out of scope.
