### ISSUE TITLE
A suggestion regarding the password generator

### ISSUE THREAD

**Issue by iam0day** [padloc/padloc#577]
I was wondering why you chose to generate passwords with a maximum of 50 characters? Is it possible to increase them to 128 characters like in the BitWarden generator? I use 128-character passwords on almost all services and would like to have this possibility in the Padloc generator too ✌️

**Comment by BrunoBernardino** [comment]
Hi @iam0day, thanks for recommending this, we'll consider implementing it on the next release!

**Comment by iam0day** [comment]
Thank you guys for accepting my proposal, amazing that you even added 150 characters 😍
