### ISSUE TITLE
Update official docker images on Dockerhub

### ISSUE THREAD

**Issue by MaKleSoft** [padloc/padloc#583]
### Discussed in https://github.com/padloc/padloc/discussions/582

<div type='discussions-op-text'>

<sup>Originally posted by **Dan6erbond** September  6, 2022</sup>
I just tried to spin up the PadLoc services (PWA and server) using Docker compose, and until I came across the way this repository references the github.com `Dockerfile-server` and `Dockerfile-pwa` images, I noticed that it was spinning up a completely wrong (maybe old/outdated) container that had some issues.

This not only proposes a security risk, but it makes PadLoc incompatible with Kubernetes deployments and modern container environments. It requires users to build their own images, which is more advanced, and would also make deployment instructions a lot easier, if people could just fetch the containers from a public source.</div>

**Comment by MaKleSoft** [comment]
Since docker hub does no longer provide automated builds, we'll probably have to create a github action for this. @BrunoBernardino Can you take care of this?

**Comment by darkpixel** [comment]
If you just keep updating the ```latest``` tag, it make it impossible to ensure you are running a specific version.

How do I know if I'm running ```padloc:latest``` that you released 3 weeks ago verses a release from 2 hours ago?

Images should be deployed with a version number (i.e. ```image: padloc/pwa:4.1.0```).  If there ends up being a problem with a new release, you can roll back by providing a specific version--like ```image: padloc/pwa:3.9.9```.

**Comment by BrunoBernardino** [comment]
@darkpixel yes, that's what we'll be doing going forward. There was a problem with the v.4.1.0 release where the tag was just `v` and to avoid confusion we removed it. Once 4.2.0 gets out, dockerhub tags should be automatically created on releases.

**Comment by darkpixel** [comment]
Apologies--I totally missed it digging through the github actions. :)
