### ISSUE TITLE
[BUG] Failed to verify auth token

### ISSUE THREAD

**Issue by detobel36** [padloc/padloc#585]
Hello,

When I try to login from a computer on my padloc (self hosted), I have the error "Failed to verify auth token".

So, I enter my email, the system doesn't detect that it's an existing account... So I enter a "wrong" password, I confirm, and then padloc detect that my account exist. Thus, it ask me to connect (with my password).

I receive this question ("trust this device ?"):   
![image](https://user-images.githubusercontent.com/5373615/188798752-834542f7-c2a4-4703-801b-8abd51af695a.png)

Then I have the error message:   
![image](https://user-images.githubusercontent.com/5373615/188798781-8a05adf8-0a49-41a4-af92-c8c0aab27e0a.png)

Here is the console log:
![188798737-c29ac54e-eb19-4739-a7ed-257a1e989203](https://user-images.githubusercontent.com/5373615/188799473-5908bc20-f45b-4c01-82ca-aaae3d844fe6.png)

I don't have any error in back.

How can I debug ?  I see in the URL that "authToken" is defined... I supposed it's not the correct one, but don't know how to fix that xD

Small information: date and hour of my computer and my server are the same.

**Comment by BrunoBernardino** [comment]
Thanks for reporting this @detobel36 ! Can you clear cache? The auth token could've been stored in the browser for a previous user/version, for example. 

To help debug, perhaps check the server logs as well for any useful information, do you see anything there?

**Comment by detobel36** [comment]
Clear cache doesn't help    
I try with another browser and same error...

The only log I have is this:
![Capture](https://user-images.githubusercontent.com/5373615/188815895-b712be12-da16-496d-8c5d-0cc70f42ee83.PNG)

Is there a parameter that I can change to have "debug" information ?

**Comment by BrunoBernardino** [comment]
Thanks @detobel36 . Any idea @MaKleSoft ?

**Comment by detobel36** [comment]
Notice that the application work perfectly with my Android (PWA) and my Linux computer (ubuntu 20.04 AND (recently) 22.04).

But here it's my professionnal windows computer (anti-virus is present).

**Comment by BrunoBernardino** [comment]
Ok, does it work [if you use docker](https://github.com/padloc/padloc/tree/main/docs/examples/hosting/docker/basic) instead? Or are you already using docker?

**Comment by detobel36** [comment]
I can't use docker, I don't have enough memory space 😕

**Comment by BrunoBernardino** [comment]
Ok, leaving it for @MaKleSoft to chime in, I'm not sure what could be happening without having to stop what I'm doing for v4.1.0 and debug further on a windows machine.

**Comment by LNCrafty** [comment]
Getting the same Behavior after Upgrading and trying to login to a brand new device. 
Also the Server no longer recognizes that im already registered
Only after the complete registration prozess I get a popup that asks me if I just wanna logon.
But e.g. the first request also returns that im not registered.

{"result":{"accountStatus":"**unregistered**","deviceTrusted":false,"provisioning":{"id":"e2ee9467b3cb8325a6ea5b20a3ef710a10bdb136","email":"*****","accountId":"aed23949-9c3d-48a4-b908-bdf76d06b7a7","status":"active","statusLabel":"","statusMessage":"","quota":{"vaults":-1,"storage":-1,"kind":"accountquota","version":"4.0.0"},"features":{"createOrg":{"disabled":false,"hidden":false,"kind":"feature","version":"4.0.0"},"quickUnlock":{"disabled":false,"hidden":false,"kind":"feature","version":"4.0.0"},"manageAuthenticators":{"disabled":false,"hidden":false,"kind":"feature","version":"4.0.0"},"manageSessions":{"disabled":false,"hidden":false,"kind":"feature","version":"4.0.0"},"manageDevices":{"disabled":false,"hidden":false,"kind":"feature","version":"4.0.0"},"attachments":{"disabled":false,"hidden":false,"kind":"feature","version":"4.0.0"},"securityReport":{"disabled":false,"hidden":false,"kind":"feature","version":"4.0.0"},"billing":{"disabled":false,"hidden":false,"kind":"feature","version":"4.0.0"},"totpField":{"disabled":false,"hidden":false,"kind":"feature","version":"4.0.0"},"notesField":{"disabled":false,"hidden":false,"kind":"feature","version":"4.0.0"},"itemHistory":{"disabled":false,"hidden":false,"kind":"feature","version":"4.0.0"},"kind":"accountfeatures","version":"4.0.0"},"orgs":[],"kind":"accountprovisioning","version":"4.0.0"},"kind":"completeauthrequestresponse","version":"4.0.0"},"kind":"response","version":"4.0.0"}

after the registration UI
method | "createAccount"
{"result":null,"error":**{"code":"account_exists","message":"This account already exists!"}**,"kind":"response","version":"4.0.0"}

And then the error from above
Thats the last reponse recieved
{"result":null,"error":{"code":"email_verification_failed","message":"Failed to verify auth token"},"kind":"response","version":"4.0.0"}

**Comment by LNCrafty** [comment]
Also another hint. Im using still the data from a 3.x.x padloc installation. Seems like a new user works fine, just the old ones are tricky

**Comment by BrunoBernardino** [comment]
Hmm... The only thing we had to consider when migrating data between versions was creating an `id` property/column in the `auth` table as a simple SHA-1 hash of the `email` property/column, and adding `accountStatus` to it, which is probably why you're getting this problem.

That extra bit of information helped tremendously @LNCrafty !

Our script for that migration also included changing database backends, so it wouldn't be useful to you, but something that might help/work is this (untested, might need tweaks), I've shared at https://gist.github.com/BrunoBernardino/5b44504cd03bbbf81a56aa2f6728d843

**Comment by detobel36** [comment]
I have an error when I try to execute the script

![image](https://user-images.githubusercontent.com/5373615/191175274-17d96e9c-36c1-4fa2-bf74-77e40bbc0ff8.png)

**Comment by BrunoBernardino** [comment]
I've updated the script for those two errors, you can check it out again.

**Comment by detobel36** [comment]
Perfect, script fix the problem ! 💯
