### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by repka3** [padloc/padloc#619]
![Screenshot 2022-10-22 144807](https://user-images.githubusercontent.com/694917/197339797-50b9a618-4306-4a08-a3fc-2d17d8dc15eb.png)

Hello, I have tried both git clone npm ci , npm run dev... and by simply using the docker up with the simplest definition. Both starts and seems fine, but when I go to localhost:8080/start and insert whatever email it simply say: "Authentication failed. The app could not enstabilish connection.....". No more error in console, no more information. Thats it. How Am I suppose to test di app in locale ?

**Comment by BrunoBernardino** [comment]
What do you see in the browser's console (I assume it's not Chrome)? It's likely the `crypto.subtle` API isn't available because you're not in `https://`, so you need to use a browser that accepts that with `http://`, like Chrome.

**Comment by repka3** [comment]
As you can see I'm using Chrome. But yeah I'm on http, not https. If I switch to https "This site can’t be reached". I probably need to use lets encrypt and switch to proper https.  Thanks, but I was looking for something that can be used completly offline on an offline network. If this software need your server as auth, this answer my question. Thanks for your time.

![Screenshot 2022-10-22 144807](https://user-images.githubusercontent.com/694917/197341457-a8748b6e-7b46-4685-bcb3-2013f6a80f2f.png)

**Comment by BrunoBernardino** [comment]
Alright, this is something else, then. The server doesn't seem to be up. You should have some error/logging in the console you're running `npm run dev` or `docker-compose` from (`docker logs padloc_server_1 -f`, for example). What do you see there?

**Comment by repka3** [comment]
after restarting both container I got a message sent but not message in the email lol. Anyway no problem.
Thanks for your time.

> @padloc/server@4.1.0 start
> ts-node src/init.ts

Starting SCIM server on port 5000
Starting server on port 3000
Server started with config:  {
    "server": {
        "clientUrl": "http://localhost:8080",
        "reportErrors": "",
        "maxRequestAge": 3600000,
        "verifyEmailOnSignup": true,
        "defaultAuthTypes": [
            "email"
        ],
        "scimServerUrl": "http://localhost:5000",
        "admins": []
    },
    "transport": {
        "backend": "http",
        "http": {
            "port": 3000,
            "maxRequestSize": 1000000000,
            "allowOrigin": "*",
            "healthCheckPath": "/healthcheck"
        }
    },
    "email": {
        "backend": "console"
    },
    "data": {
        "backend": "leveldb",
        "leveldb": {
            "dir": "/data"
        }
    },
    "attachments": {
        "backend": "fs",
        "fs": {
            "dir": "./attachments"
        }
    },
    "logging": {
        "backend": "void"
    },
    "auth": {
        "types": [
            "email",
            "totp"
        ],
        "email": {
            "backend": "console"
        },
        "totp": {
            "interval": 30,
            "digits": 6,
            "hash": "SHA-1",
            "window": 1
        }
    },
    "provisioning": {
        "backend": "basic",
        "basic": {
            "default": {
                "status": "active",
                "statusLabel": "",
                "statusMessage": ""
            },
            "secretKey": "[secret redacted]",
            "portalSecret": "[secret redacted]",
            "webhookSecret": "[secret redacted]"
        }
    },
    "directory": {
        "providers": [
            "scim"
        ],
        "scim": {
            "url": "http://localhost:5000",
            "port": 5000
        }
    },
    "changeLog": {
        "enabled": false,
        "excludeKinds": [
            "auth",
            "session",
            "srpsession",
            "authrequest"
        ]
    },
    "requestLog": {
        "enabled": false,
        "excludeEndpoints": [
            "get*",
            "list*"
        ]
    }
}
Message sent to myreal.email@gmail.com: {"code":"...","requestId":".."}

**Comment by BrunoBernardino** [comment]
That seems to be going well, then. Did you try the code in that log? Emails aren't sent unless you've setup SMTP, for example, you'll only see their info in the logs.

**Comment by repka3** [comment]
yes, I can login with that code and now I can see the app interface.

**Comment by pawan-saxena** [comment]
The issue is either due to:
1. The .env file is missing or the environment variables are not accessible to node server which is run by lerna.
2. version mismatch of node.js. Most probably the cause is use node - 14.x with padloc version 4.x.
Then remove node_modules folder from packages/padloc and packages/server and from root directory of project.

After that do : npm ci and npm start.
Happy Coding !!!!!
