### ISSUE TITLE
Unable to find database

### ISSUE THREAD

**Issue by PraveenDWappgo** [padloc/padloc#621]
i setup this on my local computer but in little bit confused in database. where is my data store. i already install PGAdmin but nothing is here

**Comment by BrunoBernardino** [comment]
Hi @PraveenDWappgo we'd need a bit more information. The default data store is [leveldb](https://en.wikipedia.org/wiki/LevelDB) and would be at the [`./data` directory](https://github.com/padloc/padloc/blob/main/packages/server/src/storage/leveldb.ts#L17).

If you customized it in any way, it should be accessible with the settings you used.

Let me know if that helps!

**Comment by PraveenDWappgo** [comment]
i wan to know that how many databases are used in padloc. Other than level db are nay other databases too ?

**Comment by BrunoBernardino** [comment]
There's only one database. There will be multiple tables, one per "storage type", like `auth`, `account`, `accountprovisioning`, `vault`, and so on.

As for what databases are supported, you can see the current list here: https://github.com/padloc/padloc/tree/bab0b8bd00c071e3139d26f34ddc8d38c83d7e01/packages/server/src/storage
