### ISSUE TITLE
Having trouble in setting mongodb in development environment

### ISSUE THREAD

**Issue by PraveenDWappgo** [padloc/padloc#623]
I simply added .env and tried to run command 

```
npm run start -- --env=file/to/path/.env

but i am getting this as an exit code 
http-server ${PL_PWA_DIR:-dist} -s -p ${PL_PWA_PORT:-8080} --proxy ${PL_PWA_URL:-http://0.0.0.0:${PL_PWA_PORT:-8080}}?
```

i know that for running development environment i have to run:-  npm run dev 

but by default it is connecting to leveldb even after i added .env 
and once i added .env i am trying to run :- npm run start -- --env=file/to/path/.env and again getting the same error

i just need help and way to how to connect to mongodb in local environment and how to make .env work in local environment 
i am getting 
 PL_DATA_STORAGE_BACKEND was set to 'mongodb', but no related configuration was found! 
 
 Please help me with this.

**Comment by BrunoBernardino** [comment]
Hi @PraveenDWappgo can you please share your .env file (redacting sensitive information like usernames and passwords)?

**Comment by PraveenDWappgo** [comment]
This is .env file which i use in this
[](url)
[env.zip](https://github.com/padloc/padloc/files/9907510/env.zip)

**Comment by PraveenDWappgo** [comment]
![Uploading Screenshot (3).png…]()

**Comment by PraveenDWappgo** [comment]
# =============================================================================
# TRANSPORT
#
# Supported backends: http (default)
# =============================================================================

# -----------------------------------------------------------------------------
# HTTP
# -----------------------------------------------------------------------------

PL_TRANSPORT_BACKEND=http
PL_TRANSPORT_HTTP_PORT=3000
PL_TRANSPORT_HTTP_MAX_REQUEST_SIZE=1e9
PL_TRANSPORT_HTTP_ALLOW_ORIGIN=*
PL_TRANSPORT_HTTP_HEALTH_CHECK_PATH=/healthcheck


# =============================================================================
# EMAIL
#
# Supported backends: smtp, console (default)
# =============================================================================

# -----------------------------------------------------------------------------
# CONSOLE
# 
# Just prints a text version of all emails to stdout
# -----------------------------------------------------------------------------

PL_EMAIL_BACKEND=console

# -----------------------------------------------------------------------------
# SMTP
# 
# Use smtp protocol for sending emails
# -----------------------------------------------------------------------------

PL_EMAIL_BACKEND=smtp
PL_EMAIL_SMTP_HOST=localhost
PL_EMAIL_SMTP_PORT=1025
PL_EMAIL_SMTP_SECURE=false
PL_EMAIL_SMTP_IGNORE_TLS=false
PL_EMAIL_SMTP_USER=""
PL_EMAIL_SMTP_PASSWORD=""
PL_EMAIL_SMTP_TEMPLATE_DIR=""
PL_EMAIL_SMTP_FROM=""


# =============================================================================
# DATA STORAGE
#
# Supported backends: void, memory, leveldb (default), mongodb, postgres
# =============================================================================

# -----------------------------------------------------------------------------
# VOID
# 
# Doesn't store anything. All data goes straight into the void.
# -----------------------------------------------------------------------------

# PL_DATA_BACKEND=postgres

# -----------------------------------------------------------------------------
# MEMORY
#
# Data is stored in memory only
# -----------------------------------------------------------------------------

PL_DATA_BACKEND=memory

# -----------------------------------------------------------------------------
# LEVELDB
#
# Use embedded leveldb as storage backend: https://github.com/level/level
# -----------------------------------------------------------------------------

PL_DATA_BACKEND=postgres
# PL_DATA_LEVELDB_DIR=./data

# -----------------------------------------------------------------------------
# MONGODB
#
# Use mongodb as storage backend: https://github.com/mongodb/node-mongodb-native
# -----------------------------------------------------------------------------

PL_DATA_BACKEND=mongodb
PL_DATA_MONGODB_HOST=localhost
PL_DATA_MONGODB_PORT=27017
PL_DATA_MONGODB_PROTOCOL=mongodb
PL_DATA_MONGODB_USERNAME=""
PL_DATA_MONGODB_PASSWORD=""
PL_DATA_MONGODB_DATABASE=padloc
PL_DATA_MONGODB_AUTH_DATABASE=""
PL_DATA_MONGODB_TLS=false
PL_DATA_MONGODB_TLS_CAFILE=""
PL_DATA_MONGODB_ACKNOWLEDGE_WRITES=true
PL_DATA_MONGODB_MAX_SIZE=""
PL_DATA_MONGODB_MAX_DOCUMENTS=""

# -----------------------------------------------------------------------------
# POSTGRES
#
# Use postgresql as storage backend: https://www.npmjs.com/package/pg
# -----------------------------------------------------------------------------


# PL_DATA_POSTGRES_HOST=localhost
# PL_DATA_POSTGRES_PORT=5432
# PL_DATA_POSTGRES_DATABASE=padloc
# PL_DATA_POSTGRES_USER=postgres
# PL_DATA_POSTGRES_PASSWORD=12345
# PL_DATA_POSTGRES_TLS=false
# PL_DATA_POSTGRES_TLS_CAFILE=""
# PL_DATA_POSTGRES_TLS_REJECT_UNAUTHORIZED=true


# =============================================================================
# ATTACHMENT STORAGE
#
# Supported backends: memory (default), fs, s3
# =============================================================================

# -----------------------------------------------------------------------------
# MEMORY
#
# Attachments are stored in memory only
# -----------------------------------------------------------------------------

PL_ATTACHMENTS_BACKEND=memory

# -----------------------------------------------------------------------------
# FS
#
# Uses the local file system to store attachments
# -----------------------------------------------------------------------------

PL_ATTACHMENTS_BACKEND=fs
PL_ATTACHMENTS_FS_DIR=./attachments

# -----------------------------------------------------------------------------
# S3
#
# Uses a S3-compatible object storage to store attachments
# -----------------------------------------------------------------------------

PL_ATTACHMENTS_BACKEND=s3
PL_ATTACHMENTS_S3_ENDPOINT=[required]
PL_ATTACHMENTS_S3_REGION=[required]
PL_ATTACHMENTS_S3_ACCESS_KEY_ID=[required]
PL_ATTACHMENTS_S3_SECRET_ACCESS_KEY=[required]
PL_ATTACHMENTS_S3_BUCKET=[required]


# =============================================================================
# LOGGING
#
# Supported backends: void (default), mongodb, postgres, mixpanel
# =============================================================================

# -----------------------------------------------------------------------------
# VOID
#
# Don't log at all
# -----------------------------------------------------------------------------

PL_LOGGING_BACKEND=void

# -----------------------------------------------------------------------------
# MONGODB
#
# Use mongodb for log storage
# -----------------------------------------------------------------------------

PL_LOGGING_BACKEND=mongodb
PL_LOGGING_MONGODB_HOST=localhost
PL_LOGGING_MONGODB_PORT=27017
PL_LOGGING_MONGODB_PROTOCOL=mongodb
PL_LOGGING_MONGODB_USERNAME=""
PL_LOGGING_MONGODB_PASSWORD=""
PL_LOGGING_MONGODB_DATABASE=padloc
PL_LOGGING_MONGODB_AUTH_DATABASE=""
PL_LOGGING_MONGODB_TLS=false
PL_LOGGING_MONGODB_TLS_CAFILE=""
PL_LOGGING_MONGODB_ACKNOWLEDGE_WRITES=true
PL_LOGGING_MONGODB_MAX_SIZE=""
PL_LOGGING_MONGODB_MAX_DOCUMENTS=""

# -----------------------------------------------------------------------------
# POSTGRES
#
# Use postgresql as log storage: https://www.npmjs.com/package/pg
# -----------------------------------------------------------------------------

PL_LOGGING_BACKEND=postgres
PL_LOGGING_POSTGRES_HOST=localhost
PL_LOGGING_POSTGRES_PORT=5432
PL_LOGGING_POSTGRES_DATABASE=padloc
PL_LOGGING_POSTGRES_USER=postgres
PL_LOGGING_POSTGRES_PASSWORD=12345
PL_LOGGING_POSTGRES_TLS=false
PL_LOGGING_POSTGRES_TLS_CAFILE=""
PL_LOGGING_POSTGRES_TLS_REJECT_UNAUTHORIZED=true

# -----------------------------------------------------------------------------
# MIXPANEL
#
# Send logs to mixpanel
# -----------------------------------------------------------------------------

PL_LOGGING_BACKEND=mixpanel
PL_LOGGING_MIXPANEL_TOKEN=[required]
PL_LOGGING_MIXPANEL_EXCLUDE_EVENTS=""


# =============================================================================
# AUTHENTICATION
#
# Supported types: email, webauthn_platform, webauthn_portable, totp, public_key, openid
# =============================================================================

PL_AUTH_TYPES=email,totp

# -----------------------------------------------------------------------------
# EMAIL AUTHENTICATION
#
# Send verfication code via email.
# -----------------------------------------------------------------------------

# By default, this uses the config from PL_EMAIL_...
# To use a different configuration, you can use the same environment variables,
# but prefixed with PL_AUTH_EMAIL_... instead of PL_EMAIL

# -----------------------------------------------------------------------------
# WEBAUTHN
#
# Configuration for webautn authentication types. Required for both
# webauthn_portable and webauthn_platform
# -----------------------------------------------------------------------------

PL_AUTH_WEBAUTHN_RP_NAME=[required]
PL_AUTH_WEBAUTHN_RP_ID=[required]
PL_AUTH_WEBAUTHN_ORIGIN=[required]

# -----------------------------------------------------------------------------
# TOTP
#
# Configration for authentication via time-based one-time passwords
# https://datatracker.ietf.org/doc/html/rfc6238
# -----------------------------------------------------------------------------

PL_AUTH_TOTP_INTERVAL=30
PL_AUTH_TOTP_DIGITS=6
PL_AUTH_TOTP_HASH=SHA-1
PL_AUTH_TOTP_WINDOW=1

# -----------------------------------------------------------------------------
# OPENID
#
# Configration for authentication via Oauth/OpenID
# -----------------------------------------------------------------------------

PL_AUTH_OPENID_CLIENT_ID=[required]
PL_AUTH_OPENID_CLIENT_SECRET=[required]
PL_AUTH_OPENID_AUTHORIZATION_ENDPOING=[required]
PL_AUTH_OPENID_TOKEN_ENDPOINT=[required]
PL_AUTH_OPENID_TOKEN_REDIRECT_URI=[required]


# =============================================================================
# PROVISIONING
#
# Supported backends: simple (default), stripe, directory
# =============================================================================

# -----------------------------------------------------------------------------
# BASIC PROVISIONING
# 
# Basic provisioner which allows managing provisioning users and orgs through
# database entries.
# -----------------------------------------------------------------------------

PL_PROVISIONING_BACKEND=basic
PL_PROVISIONING_BASIC_DEFAULT_STATUS=active
PL_PROVISIONING_BASIC_DEFAULT_STATUS_LABEL=""
PL_PROVISIONING_BASIC_DEFAULT_STATUS_MESSAGE=""
PL_PROVISIONING_BASIC_DEFAULT_ACTION_URL=""
PL_PROVISIONING_BASIC_DEFAULT_ACTION_LABEL=""

# -----------------------------------------------------------------------------
# STRIPE PROVISIONING
# 
# Manage provisioning via stripe
# -----------------------------------------------------------------------------

PL_PROVISIONING_BACKEND=stripe
PL_PROVISIONING_STRIPE_SECRET_KEY=[required]
PL_PROVISIONING_STRIPE_PUBLIC_KEY=[required]
PL_PROVISIONING_STRIPE_WEBHOOK_PORT=[required]

# -----------------------------------------------------------------------------
# DIRECTORY PROVISIONING
# 
# Manage provisioning via directory (only SCIM supported for now)
# -----------------------------------------------------------------------------

PL_PROVISIONING_BACKEND=directory
PL_DIRECTORY_PROVIDERS=scim
PL_DIRECTORY_SCIM_URL=http://localhost:5000
PL_DIRECTORY_SCIM_PORT=5000

# =============================================================================
# SERVER
#
# Basic server config
# =============================================================================

PL_SERVER_CLIENT_URL=http://localhost:8080
PL_SERVER_REPORT_ERRORS=webmaster@example.com
PL_SERVER_MAX_REQUEST_AGE=3600000
PL_SERVER_VERIFY_EMAIL_ON_SIGNUP=true
PL_SERVER_DEFAULT_AUTH_TYPES=email
PL_SERVER_DISABLE_SIGNUP=false
PL_SERVER_SCIM_SERVER_URL=http://localhost:5000
PL_SERVER_ADMINS=admin@example.com

# =============================================================================
# PWA
#
# Config for progressive web app
# =============================================================================

PL_PWA_PORT=8080
PL_PWA_DIR=./dist

# =============================================================================
# ADMIN
#
# Config for Admin's progressive web app
# =============================================================================

PL_ADMIN_PORT=9090
PL_ADMIN_DIR=./dist
PL_ADMIN_URL_PATH=/
PL_ADMIN_URL=http://localhost:9090

# =============================================================================
# CHANGE LOG
#
# Log database updates. Useful as an audit trail or for debugging
# =============================================================================

PL_CHANGE_LOG_ENABLED=false
PL_CHANGE_LOG_EXCLUDE_KINDS=auth,session,srpsession,authrequest

SEE STORAGE OPTIONS...
PL_CHANGE_LOG_STORAGE_...

# =============================================================================
# REQUEST LOG
#
# Log requests sent to the server. Useful as an audit trail or for debugging
# =============================================================================

PL_REQUEST_LOG_ENABLED=false
PL_REQUEST_LOG_EXCLUDE_KINDS=get*,list*

# SEE STORAGE OPTIONS...
# PL_REQUEST_LOG_STORAGE_...

**Comment by PraveenDWappgo** [comment]
everything is in .env file?

**Comment by MaKleSoft** [comment]
@PraveenDWappgo Can you please also post the full output of the `npm run start` command?

**Comment by PraveenDWappgo** [comment]
C:\Users\asus\Desktop\Padloc-K>npm run start

> padloc@4.1.0 start
> npm run pwa:build && lerna run --scope '@padloc/{server,pwa}' --parallel start


> padloc@4.1.0 pwa:build
> lerna run build --scope @padloc/pwa

lerna notice cli v5.1.8
lerna notice filter including "@padloc/pwa"
lerna info filter [ '@padloc/pwa' ]
lerna info Executing command in 1 package: "npm run build"
lerna info run Ran npm script 'build' in '@padloc/pwa' in 20.9s:

> @padloc/pwa@4.1.0 build
> webpack

47 assets
885 modules
webpack 5.52.0 compiled successfully in 16684 ms
lerna success run Ran npm script 'build' in 1 package in 20.9s:
lerna success - @padloc/pwa
lerna notice cli v5.1.8
lerna notice filter including "@padloc/{server,pwa}"
lerna info filter [ '@padloc/{server,pwa}' ]
lerna info Executing command in 2 packages: "npm run start"
@padloc/pwa: > @padloc/pwa@4.1.0 start
@padloc/pwa: > http-server ${PL_PWA_DIR:-dist} -s -p ${PL_PWA_PORT:-8080} --proxy ${PL_PWA_URL:-http://127.0.0.1:${PL_PWA_PORT:-8080}}?
@padloc/server: > @padloc/server@4.1.0 start
@padloc/server: > ts-node src/init.ts
lerna ERR! npm run start exited 1 in '@padloc/pwa'
lerna ERR! npm run start stdout:

> @padloc/pwa@4.1.0 start
> http-server ${PL_PWA_DIR:-dist} -s -p ${PL_PWA_PORT:-8080} --proxy ${PL_PWA_URL:-http://127.0.0.1:${PL_PWA_PORT:-8080}}?

lerna ERR! npm run start exited 1 in '@padloc/pwa'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.

C:\Users\asus\Desktop\Padloc-K>

**Comment by PraveenDWappgo** [comment]
Please help me with this.

**Comment by MaKleSoft** [comment]
Is that the full output? You should get something like `Starting server with config:` and then a JSON representation of the full config. Can you perhaps try to start the server directly from the `packages/server` directory. There seems to be an error starting the pwa too but it doesn't show the error, so maybe also try to run `npm run start` directly from the `packages/pwa` directory.

**Comment by PraveenDWappgo** [comment]
getting this response after hit npm run start under packages/pwa 

C:\Users\asus\Desktop\padloc\packages\pwa>npm run start

> @padloc/pwa@4.1.0 start
> http-server ${PL_PWA_DIR:-dist} -s -p ${PL_PWA_PORT:-8080} --proxy ${PL_PWA_URL:-http://0.0.0.0:${PL_PWA_PORT:-8080}}?

Also not getting any JSON Representation that your asking for because server is not even started as you can check output mentioned above.

MY MOTO IS TO JUST CONNECT MONGODB IN DEV ENVIRONMENT PLEASE HELP ME WITH THAT I READED ALL THE INSTRUCTIONS AND FOLLOWED THE SAME.

**Comment by PraveenDWappgo** [comment]
Please help me with this.

**Comment by BrunoBernardino** [comment]
Are you running this from a Windows machine?

**Comment by MaKleSoft** [comment]
Closing this due to missing feedback.
