### ISSUE TITLE
Extension Popup Window on Chromium is Zero Width

### ISSUE THREAD

**Issue by tweidinger** [padloc/padloc#627]
The latest extension (4.1.0) installed from the Chrome Web Store is displaying only scrollbars when clicking on the extension icon. 

![image](https://user-images.githubusercontent.com/28728469/202692582-cca7d6d7-4c69-4ec8-a341-938bba91814d.png)

Chromium Version 107.0.5304.110 (Official Build) Arch Linux (64-bit)
Wayland (Sway) with DPI scaling of 2

**Comment by BrunoBernardino** [comment]
Thanks for reporting this @tweidinger ! I'm not having this problem on Gnome on Arch Linux nor Cinnamon on Mint Linux. Can you try downloading the `.crx` file from https://github.com/padloc/padloc/releases/tag/v4.1.0 and install from there directly? Also, if you resize the popup, does it not persist?

Which Desktop Environment are you using?

**Comment by tweidinger** [comment]
Hey thanks for the ultra quick feedback @BrunoBernardino.
I could reproduce the issue with the extension file from the build assets.
Resizing was not possible, as the borders did not indicate some sort of slider/extending mechanism.

I am using Manjaro with Sway. The Firefox extension works fine.

**Comment by BrunoBernardino** [comment]
Thanks @tweidinger , we'll have to try and reproduce this with Sway, to see what can be done, if anything. I'm sorry I missed that indication in the initial report. I didn't know about it's existence until now.

**Comment by tweidinger** [comment]
I found another fresh installed extension (deepl) to behave the same way. I assume this is a chromium (scaling) bug by now.

**Comment by BrunoBernardino** [comment]
Thanks @tweidinger ! Seems like we can close this, then. If there's any new information, feel free to update here.
