### ISSUE TITLE
Biometric authentication failed! Canceling Setup. (Reason: This multi factor authentication type is not supported by this server!)

### ISSUE THREAD

**Issue by AnkitCWappgo** [padloc/padloc#647]
![Screenshot_2022-12-14-14-10-12-481_com brave browser](https://user-images.githubusercontent.com/82019650/207547998-702648c5-4961-461f-bd19-7df848e7d10c.jpg)

**Comment by BrunoBernardino** [comment]
Thanks @AnkitCWappgo ! Can you tell us a bit about what's the device/OS/version you're using?

**Comment by AnkitCWappgo** [comment]
Redmi Note 10/Android/12

**Comment by BrunoBernardino** [comment]
Is it a fingerprint sensor you're trying to use? We haven't received any report of any of them not working. Is it possible there's some definition that could prevent proper access of the app to it?

**Comment by BrunoBernardino** [comment]
@AnkitCWappgo can you elaborate? Is this error happening on the mobile device's web browser, connecting to your deployed server, then?

**Comment by AnkitCWappgo** [comment]
I m deploying this code on my own server.And when I am installing  pwa on android or any other device ,the biometeric setup does not work .So can you help me with the biometeric setup

**Comment by BrunoBernardino** [comment]
Do you get any error in the server when that happens?

**Comment by AnkitCWappgo** [comment]
No I didn't get any error on server.

**Comment by AnkitCWappgo** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/82019650/209629696-a9b538e5-535d-4d1f-ac47-ba3216ad22b9.png">

**Comment by AnkitCWappgo** [comment]
<img width="740" alt="image" src="https://user-images.githubusercontent.com/82019650/209629732-396e5e0e-1f53-4e03-b32a-4afbeb594761.png">

**Comment by BrunoBernardino** [comment]
@AnkitCWappgo that's in the browser, what about the server?

**Comment by working-name** [comment]
@AnkitCWappgo did you figure it out?
