### ISSUE TITLE
Tauri Updater Process Regression

### ISSUE THREAD

**Issue by tweidinger** [padloc/padloc#652]
I just noticed that the latest release did not lead to my local Tauri application being updated.

After researching the issue I found that the current configuration doesn't include the proper link to the updater metadata.

https://github.com/padloc/padloc/blob/988cf791d8b6a7351940e5d0c9ec2962411d4876/packages/tauri/src-tauri/tauri.conf.json#L59

https://github.com/padloc/padloc/blob/988cf791d8b6a7351940e5d0c9ec2962411d4876/packages/tauri/build-tauri-conf.js#L28

The link seems to be mixed up. 
I found [https://github.com/padloc/padloc/releases/latest/download/tauri-update.json](https://github.com/padloc/padloc/releases/latest/download/tauri-update.json) to be properly resolving to the latest updater metadata. Note that it is `/releases/latest/download` instead of `/releases/download/latest/`.

Since this requires me to manually update to fix this (to a not yet released version), a notification for the Tauri users would be very welcome.

**Comment by BrunoBernardino** [comment]
@tweidinger nice catch, thank you for this! We'll fix it for an upcoming version.
