### ISSUE TITLE
Android app trying to connect to localhost

### ISSUE THREAD

**Issue by ondrejnedoma** [padloc/padloc#666]
I've self hosted a server and pwa via docker and that seems to be working without any issues. But now I've tried to compile the Android Cordova app. After installing the APK and opening the app, I see the spinner for a second, then a black screen. When I tried `adb logcat` and also HTTP Toolkit proxy, I can clearly see that my PL_SERVER_URL environmental variable has been ignored and the app is trying to connect to localhost.

`01-07 13:44:04.542 14214 14274 I cr_X509Util: Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
01-07 13:44:04.545 14214 14275 E chromium: [ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -202
01-07 13:44:04.556 14214 14214 I chromium: [INFO:CONSOLE(113336)] "Uncaught (in promise) ReferenceError: device is not defined", source: https://localhost/main.js (113336)`

Also tried editing webpack.config.js line 55 from
PL_SERVER_URL: `http://localhost:${process.env.PL_SERVER_PORT || 3000}`,
to
PL_SERVER_URL: process.env.PL_SERVER_URL

which did not help either.

**Comment by BrunoBernardino** [comment]
Thanks for reaching out! What was the command you used to build the Android app?

**Comment by ondrejnedoma** [comment]
`npm ci && PL_SERVER_URL=https://padloc-server.myhomelab.net npm run cordova:build:android`

**Comment by BrunoBernardino** [comment]
That should be enough. Any thoughts @MaKleSoft ?

**Comment by ondrejnedoma** [comment]
I'm going to include the whole process I've undergone because I am definitely missing something:

- Install node 16, which includes npm 8
- Download and install Android studio, install SDK 30, platform tools, and cli tools
- Download Gradle 7.2, extract to a folder on C:\, add C;\gradle-7.2\bin to PATH
- Add platform tools to PATH
- Create an environmental variable called ANDROID_SDK_ROOT with SDK tools
- Clone this repo (padloc/padloc)
- Extract the zip, CD into the folder, and run the above command

I've also verified that my environmental variable is there, by running
`PL_SERVER_URL=https://padloc-server.myhomelab.net node`
and inside node
`console.log(process.env)`
which indeed confirmed that it is present

**Comment by MaKleSoft** [comment]
@ondrejnedoma I think you misread the error message - It has anything to do with the server url. The stuff loaded from localhost is the bundled javascript. This is the relevant part of the error message I think: `Uncaught (in promise) ReferenceError: device is not defined`. Can you debug the web view (you can do that from Chrome on your computer via `chrome://inspect` and figure out where that error happens exactly?

**Comment by ondrejnedoma** [comment]
Well. It suddenly started working. I swear I did nothing different, just extracting the zipped git repo over and over and compiling the app fresh. But here I am, with a working apk connecting to my own server.
