### ISSUE TITLE
Favicons should be load by server

### ISSUE THREAD

**Issue by qaqland** [padloc/padloc#668]
It is my guess that padloc load website favicons from client. Please correct me if I'm wrong :)

Favicons should be load by server. There are reasons:

1. Duckduckgo has been blocked in some areas hence it can't work.
2. Five Eyes or other office can detect your store items by the favicon request from your phone.

**Comment by BrunoBernardino** [comment]
@qaqland thanks for the suggestion, but this would effectively be putting trust in Padloc's server, which goes against our threat/security model.

It seems that for your concern, a simple VPN/proxy would be a much better option in general. I hope that makes sense!

@MaKleSoft feel free to correct me if I'm wrong, here.

**Comment by qaqland** [comment]
> @qaqland thanks for the suggestion, but this would effectively be putting trust in Padloc's server, which goes against our threat/security model.

In fact, we can cache favicon as user's data and sync it like password. And provide a button in setting to reflash all favions from client only once.
