### ISSUE TITLE
Something trying to contact `raw.githubusercontent.com` when starting server in docker-compose project

### ISSUE THREAD

**Issue by titus-anromedonn** [padloc/padloc#672]
I'm not sure what, but something is trying to contact `raw.githubusercontent.com` when starting the server. If running on a network with limited connectivity, this won't work. I have been unsuccessful in finding what is doing this. A small exception message can be found below

```
uncaught exception:  getaddrinfo ENOTFOUND raw.githubusercontent.com Error: getaddrinfo ENOTFOUND raw.githubusercontent.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) exiting...
```

Some background info

* I am running this in docker via docker-compose.
* I have been following the docker-compose example, using the latest docker images available 
* I have tried simply to let `raw.githubusercontent.com` to `127.0.0.1` via the `extra_hosts` attribute in my compose file but then there is an issue trying to connect to that url because I am obviously not running anything via `https`. If I do that, then I get the following error. Any insight would be helpful.    
```
uncaught exception:  connect ECONNREFUSED 127.0.0.1:443 Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) exiting...
```

**Comment by titus-anromedonn** [comment]
After further investigation, I have tracked it down to the `node-geolite2-redist` library. Is there any way to mitigate this?

**Comment by BrunoBernardino** [comment]
@titus-anromedonn there is no problem to setting `location = undefined` at all, we simply use that for people to see the location information in their sessions and more easily identify the devices/sessions.
