### ISSUE TITLE
Allow Managing (editing / deleting / reordering) tags

### ISSUE THREAD

**Issue by MaKleSoft** [padloc/padloc#673]
This would probably be a new view under Settings. Features:

- [ ] Create Tags
- [ ] Delete Tags, automatically removing them from all items
- [ ] Rename Tags, automatically updating tags on affected items
- [ ] Reorder Tags, changing the order they appear in the menu and on vault items

**Comment by BrunoBernardino** [comment]
@MaKleSoft am I missing something? I don't see this view anywhere in the UI or code.

**Comment by MaKleSoft** [comment]
@BrunoBernardino Should be under Settings/Tags. Although it's not available on iOS or Android yet.

**Comment by BrunoBernardino** [comment]
How did I miss this!?!?!? Has this been here ever since 4.3.0!?

**Comment by MaKleSoft** [comment]
Yep 😊

**Comment by BrunoBernardino** [comment]
:facepalm: I've been looking for this for so long.
