### ISSUE TITLE
Stay logged in after restart

### ISSUE THREAD

**Issue by probablykasper** [padloc/padloc#678]
Would love to be able to have an option to stay logged in forever.

Not sure it's possible to do it securely in browser extensions, so for those maybe the extension can request authorization from the desktop app, and have the user press "ok".

**Comment by MaKleSoft** [comment]
I assume you mean "stay unlocked", rather than "logged in"? Or in other words, you want to be able to access your data without entering your master password even after restarting? Also, what do you mean by "restart", precisely? Restart the app? Your computer?

**Comment by probablykasper** [comment]
Yes, staying unlocked after the app (or computer) restarts

**Comment by MaKleSoft** [comment]
Yeah, I'm afraid there is no way to do this securely. The closest you're going to get is using biometric unlock. Sorry!

**Comment by probablykasper** [comment]
If Bitwarden does it then I assume it's secure. I would guess it uses the OS keychain, but don't know for sure.

And what about the suggestion for the browser extension?

**Comment by probablykasper** [comment]
Any thoughts @MaKleSoft?

**Comment by probablykasper** [comment]
You're misunderstanding. I'm not suggesting any of that, just that maybe there's a way to do it securely. Are you 100% sure there's no way to do it securely with the macOS Keychain Services API?

**Comment by MaKleSoft** [comment]
I don't claim to know every method out there (not even close), so no for course not 100%. But as far as I know, there is no way to do it securely, at least for our definition of "secure". But if you come up with something, and get a security expert to sign off on it - then we'll be happy to consider it 😉

**Comment by probablykasper** [comment]
I don't have a security expert at hand, but it seems pretty clear that this API is meant for use cases like these - would be weird for an OS to not have a basic security feature like this imo.

In [the Keychain access API documentation](
https://developer.apple.com/documentation/security/keychain_services) it's explained that apps can use it to securely store secrets like passwords and credit cards on behalf of the user, in an encrypted database.

From [the article "Using the keychain to manage user secrets"](https://developer.apple.com/documentation/security/keychain_services/keychain_items/using_the_keychain_to_manage_user_secrets#overview):
> Apps often need access to sensitive user data such as passwords, but keeping the data secure can come at a cost: If you store a data without encrypting it, you create a security risk. If instead you repeatedly prompt the user, you produce a bad user experience—one that typically causes the user to create simple passwords or else write them down.
> 
> Keychain services helps solve this problem by providing easy access to encrypted storage. Your app uses the keychain, along with minimal user interaction, to provide a good user experience. For example, consider a process like the one depicted in Figure 1 for storing an Internet password.

The [security-framework](https://github.com/kornelski/rust-security-framework) and [keyring-rs](https://github.com/hwchen/keyring-rs) crates might be helpful to look into
