### ISSUE TITLE
The most modern algorithm for hashing...

### ISSUE THREAD

**Issue by iam0day** [padloc/padloc#688]
I was wondering if you are thinking of implementing a more up-to-date algorithm such as Argon2id for hashing? As [recommended by OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#password-hashing-algorithms) and as reported by a [security researcher](https://palant.info/2023/01/23/bitwarden-design-flaw-server-side-iterations/).

**Comment by MaKleSoft** [comment]
We'd love to start using a more modern algorithm, but unfortunately we're currently limited to whatever is shipped as part of the WebCrypto api. Hopefully there going to be some progress in that area soon. See also: https://github.com/w3c/webcrypto/issues/265
