### ISSUE TITLE
Allow custom style

### ISSUE THREAD

**Issue by somoit-JSP** [padloc/padloc#690]
Hi
I would like to suggest the feature of allowing adding custom css, ... code. 
As an example of minor custom changes:

Before:
![before](https://user-images.githubusercontent.com/116510070/220947857-0c0c92d2-af69-4a69-a30e-f112b3017643.png)

After:
![after](https://user-images.githubusercontent.com/116510070/220947908-05572653-e3d0-4db6-bb8d-8494f5e489f5.png)

Thanks!

**Comment by MaKleSoft** [comment]
Not sure what you mean? If you're looking to add "custom code", why not just fork the project and make any changes you want? If you're looking to make simple changes to the theme, you can do that via [theme.css](https://github.com/padloc/padloc/blob/main/assets/theme.css). Closing as out of scope.
