### ISSUE TITLE
[Feature Request] Allow adding premium fields without premium subscription, but don't render them outside editor.

### ISSUE THREAD

**Issue by rokejulianlockhart** [padloc/padloc#698]
I want to evaluate whether Padloc fits my needs. I intend to transfer from Bitwarden. Although Bitwarden necessitates payment to generate TOTP codes, it allows the user to add the TOTP key. I want to ascertain whether Padloc can support everything that I have stored in my Bitwarden vault, such as
* Markdown text (despite `bw` not supporting that). I obviously see the option to add it, but want to see things like whether a character limit exists to ensure that no truncation occurs; and
* multiple TOTP codes. I realize that this might be in the documentation somewhere, but being able to actually see that I am able to add multiple TOTP keys to a single vault entry (which `bw` doesn't support) would incentivize me to try the subscription.

**Comment by MaKleSoft** [comment]
Thanks for your suggestion! But testing these things is kind for what the trial period is for 😉. Allowing to add premium fields but then not displaying them correctly (or not at all) feels like a dark pattern to me, and would probably not be received well. So I think we'll stick with the current model :)

**Comment by MaKleSoft** [comment]
@rokejulianlockhart You can start the trial and then immediately cancel the subscription. You'll still be able to use all premium features till the end of the trial period, but the subscription will not be renewed automatically. If you do decide you want to continue the subscription, you simply uncancel it.
