### ISSUE TITLE
pwa on docker: webCrypto is undefined

### ISSUE THREAD

**Issue by nasrudin2468** [padloc/padloc#723]
Hi there,

I've experienced a breaking error within pwa on docker:

when you try to set a password during creation of a new account the error "WebCrypto is undefined" is thrown:

![err20230912](https://github.com/padloc/padloc/assets/30647511/77323165-e86b-4872-94b0-b8ca70498b85)

How to recreate this error:

- Create compose.yaml 
- Start stack
- open http://ip:8082
- enter email (dummy@localhost)
- enter verification code from logfile
- choose password
- repeat passwort and hit "continue"

Compose Yaml used:

_version: "3.7"_
_services:
    server:
        image: padloc/server
        build:
            context: github.com/padloc/padloc.git#main
            dockerfile: Dockerfile-server
        environment:
            PL_DATA_BACKEND: leveldb
            PL_DATA_LEVELDB_DIR: /data
            PL_DATA_ATTACHMENTS_BACKEND: fs
            PL_DATA_ATTACHMENTS_DIR: /attachments
            PL_SERVER_CLIENT_URL: http://192.168.1.1:8082
            PL_EMAIL_BACKEND: console
        ports:
            - 3000:3000
            - 5000:5000
        volumes:
            - attachments:/attachments
            - data:/data
        restart: unless-stopped
    pwa:
        image: padloc/pwa
        build:
            context: github.com/padloc/padloc.git#main
            dockerfile: Dockerfile-pwa
        environment:
            PL_SERVER_URL: http://192.168.1.1:3000
            PL_PWA_URL: http://192.168.1.1:8082
        ports:
            - 8082:8080
        restart: on-failure_
  
_volumes:
    data:
      name: data_padloc
      driver: local
    attachments:      
      name: attachments_padloc
      driver: local:_

I've looked up the error online and found this on stackoverflow: 
https://stackoverflow.com/questions/73438751/crypto-webcrypto-is-undefined-in-production-deployment. 

According to this thread it "could" be a dependency problem within the image. However this is just a careful guess as I am absolutely not familiar with node.js
Not sure if it's relevant, but I also experience the log entry from https://github.com/padloc/padloc/issues/719.

Kind regards

**Comment by MaKleSoft** [comment]
The webCrypto api (and by extension Padloc itself) requires a secure context, meaning the page has to be loaded via https. You serving the page over plain http, which is not supported.
