### ISSUE TITLE
Implement browser extensions

### ISSUE THREAD

**Issue by eorroe** [padloc/padloc#82]
I'd love if this was remade into an extension that does everything the app does, but everytime I open the extension popup it ask me for my password. Instantly allows me to search by typing once unlocked, and record data can easily be copied, via keyboard.

Then I can easily paste the password while browsing the web.

Again as long as everything the app does is already possible like exporting encrypted data

Also the popup can be smaller and show recently copied passwords on the top, then reset once locked again.

**Comment by eorroe** [comment]
If this also worked via the omibox that would be amazing, where I can just:

1. Trigger omnibox keyword "padlock"
2. Type my password
3. Search for record
4. Copy record data

**Comment by MaKleSoft** [comment]
Hm, these are interesting suggestions. I have in fact been thinking about a 'lightweight' version of Padlock living as an extension in the browser somehow. The omnibox idea is new and quite intriguing. Right now priorities are elsewhere though. I'm currently in the progress of doing a full rewrite of the core app for v2.0 and I'm deferring all major changes until that is done. I'll definitely revisit this, though!

**Comment by eorroe** [comment]
Sounds good, in a couple months I'll get back to this and see if I can help somehow

**Comment by jimvonmoon** [comment]
It should be enough to make a small app for interfacing with Native Messaging API:
https://developer.chrome.com/apps/nativeMessaging
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging

Browsers' extensions could build upon that.

**Comment by MaKleSoft** [comment]
@jimvonmoon Thanks for the input! Looks like a good starting point.

**Comment by eorroe** [comment]
Oh that's nice 👌 @jimvonmoon 

Looking forward to this @MaKleSoft

**Comment by rugk** [comment]
On your website you already have a Chrome/ium extension listed? So is this solved for Chrome/ium?

Firefox is just still missing.

**Comment by rugk** [comment]
Okay, opened a new issue for that: https://github.com/padlock/padlock/issues/216

**Comment by MaKleSoft** [comment]
@rugk @eorroe @jimvonmoon Sorry we've made you wait for so long, but now the time is almost upon us! 😊In the meantime, we would love your input on features etc.: https://github.com/padloc/padloc/issues/265
